// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attachment.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EscrowCreation_DeadlineAction int32

const (
	EscrowCreation_UNDECIDED EscrowCreation_DeadlineAction = 0
	EscrowCreation_RELEASE   EscrowCreation_DeadlineAction = 1
	EscrowCreation_REFUND    EscrowCreation_DeadlineAction = 2
	EscrowCreation_SPLIT     EscrowCreation_DeadlineAction = 3
)

var EscrowCreation_DeadlineAction_name = map[int32]string{
	0: "UNDECIDED",
	1: "RELEASE",
	2: "REFUND",
	3: "SPLIT",
}
var EscrowCreation_DeadlineAction_value = map[string]int32{
	"UNDECIDED": 0,
	"RELEASE":   1,
	"REFUND":    2,
	"SPLIT":     3,
}

func (x EscrowCreation_DeadlineAction) String() string {
	return proto.EnumName(EscrowCreation_DeadlineAction_name, int32(x))
}
func (EscrowCreation_DeadlineAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{24, 0}
}

type Attachment struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{0}
}
func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (dst *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(dst, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Attachment) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type MultiOutCreation struct {
	Recipients           []*MultiOutCreation_Recipients `protobuf:"bytes,1,rep,name=recipients" json:"recipients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MultiOutCreation) Reset()         { *m = MultiOutCreation{} }
func (m *MultiOutCreation) String() string { return proto.CompactTextString(m) }
func (*MultiOutCreation) ProtoMessage()    {}
func (*MultiOutCreation) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{1}
}
func (m *MultiOutCreation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiOutCreation.Unmarshal(m, b)
}
func (m *MultiOutCreation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiOutCreation.Marshal(b, m, deterministic)
}
func (dst *MultiOutCreation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiOutCreation.Merge(dst, src)
}
func (m *MultiOutCreation) XXX_Size() int {
	return xxx_messageInfo_MultiOutCreation.Size(m)
}
func (m *MultiOutCreation) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiOutCreation.DiscardUnknown(m)
}

var xxx_messageInfo_MultiOutCreation proto.InternalMessageInfo

func (m *MultiOutCreation) GetRecipients() []*MultiOutCreation_Recipients {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type MultiOutCreation_Recipients struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiOutCreation_Recipients) Reset()         { *m = MultiOutCreation_Recipients{} }
func (m *MultiOutCreation_Recipients) String() string { return proto.CompactTextString(m) }
func (*MultiOutCreation_Recipients) ProtoMessage()    {}
func (*MultiOutCreation_Recipients) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{1, 0}
}
func (m *MultiOutCreation_Recipients) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiOutCreation_Recipients.Unmarshal(m, b)
}
func (m *MultiOutCreation_Recipients) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiOutCreation_Recipients.Marshal(b, m, deterministic)
}
func (dst *MultiOutCreation_Recipients) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiOutCreation_Recipients.Merge(dst, src)
}
func (m *MultiOutCreation_Recipients) XXX_Size() int {
	return xxx_messageInfo_MultiOutCreation_Recipients.Size(m)
}
func (m *MultiOutCreation_Recipients) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiOutCreation_Recipients.DiscardUnknown(m)
}

var xxx_messageInfo_MultiOutCreation_Recipients proto.InternalMessageInfo

func (m *MultiOutCreation_Recipients) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MultiOutCreation_Recipients) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MultiSameOutCreation struct {
	Recipients           []uint64 `protobuf:"varint,1,rep,packed,name=recipients" json:"recipients,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSameOutCreation) Reset()         { *m = MultiSameOutCreation{} }
func (m *MultiSameOutCreation) String() string { return proto.CompactTextString(m) }
func (*MultiSameOutCreation) ProtoMessage()    {}
func (*MultiSameOutCreation) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{2}
}
func (m *MultiSameOutCreation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSameOutCreation.Unmarshal(m, b)
}
func (m *MultiSameOutCreation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSameOutCreation.Marshal(b, m, deterministic)
}
func (dst *MultiSameOutCreation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSameOutCreation.Merge(dst, src)
}
func (m *MultiSameOutCreation) XXX_Size() int {
	return xxx_messageInfo_MultiSameOutCreation.Size(m)
}
func (m *MultiSameOutCreation) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSameOutCreation.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSameOutCreation proto.InternalMessageInfo

func (m *MultiSameOutCreation) GetRecipients() []uint64 {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type ArbitaryMessage struct {
	IsText               bool     `protobuf:"varint,1,opt,name=isText" json:"isText,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArbitaryMessage) Reset()         { *m = ArbitaryMessage{} }
func (m *ArbitaryMessage) String() string { return proto.CompactTextString(m) }
func (*ArbitaryMessage) ProtoMessage()    {}
func (*ArbitaryMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{3}
}
func (m *ArbitaryMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArbitaryMessage.Unmarshal(m, b)
}
func (m *ArbitaryMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArbitaryMessage.Marshal(b, m, deterministic)
}
func (dst *ArbitaryMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArbitaryMessage.Merge(dst, src)
}
func (m *ArbitaryMessage) XXX_Size() int {
	return xxx_messageInfo_ArbitaryMessage.Size(m)
}
func (m *ArbitaryMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ArbitaryMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ArbitaryMessage proto.InternalMessageInfo

func (m *ArbitaryMessage) GetIsText() bool {
	if m != nil {
		return m.IsText
	}
	return false
}

func (m *ArbitaryMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AliasAssignment struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliasAssignment) Reset()         { *m = AliasAssignment{} }
func (m *AliasAssignment) String() string { return proto.CompactTextString(m) }
func (*AliasAssignment) ProtoMessage()    {}
func (*AliasAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{4}
}
func (m *AliasAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliasAssignment.Unmarshal(m, b)
}
func (m *AliasAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliasAssignment.Marshal(b, m, deterministic)
}
func (dst *AliasAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliasAssignment.Merge(dst, src)
}
func (m *AliasAssignment) XXX_Size() int {
	return xxx_messageInfo_AliasAssignment.Size(m)
}
func (m *AliasAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_AliasAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_AliasAssignment proto.InternalMessageInfo

func (m *AliasAssignment) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *AliasAssignment) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type AccountInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{5}
}
func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (dst *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(dst, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AliasSell struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliasSell) Reset()         { *m = AliasSell{} }
func (m *AliasSell) String() string { return proto.CompactTextString(m) }
func (*AliasSell) ProtoMessage()    {}
func (*AliasSell) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{6}
}
func (m *AliasSell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliasSell.Unmarshal(m, b)
}
func (m *AliasSell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliasSell.Marshal(b, m, deterministic)
}
func (dst *AliasSell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliasSell.Merge(dst, src)
}
func (m *AliasSell) XXX_Size() int {
	return xxx_messageInfo_AliasSell.Size(m)
}
func (m *AliasSell) XXX_DiscardUnknown() {
	xxx_messageInfo_AliasSell.DiscardUnknown(m)
}

var xxx_messageInfo_AliasSell proto.InternalMessageInfo

func (m *AliasSell) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *AliasSell) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AliasBuy struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliasBuy) Reset()         { *m = AliasBuy{} }
func (m *AliasBuy) String() string { return proto.CompactTextString(m) }
func (*AliasBuy) ProtoMessage()    {}
func (*AliasBuy) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{7}
}
func (m *AliasBuy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliasBuy.Unmarshal(m, b)
}
func (m *AliasBuy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliasBuy.Marshal(b, m, deterministic)
}
func (dst *AliasBuy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliasBuy.Merge(dst, src)
}
func (m *AliasBuy) XXX_Size() int {
	return xxx_messageInfo_AliasBuy.Size(m)
}
func (m *AliasBuy) XXX_DiscardUnknown() {
	xxx_messageInfo_AliasBuy.DiscardUnknown(m)
}

var xxx_messageInfo_AliasBuy proto.InternalMessageInfo

func (m *AliasBuy) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type AssetIssuance struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Quantity             uint64   `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	Decimals             uint32   `protobuf:"varint,4,opt,name=decimals" json:"decimals,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetIssuance) Reset()         { *m = AssetIssuance{} }
func (m *AssetIssuance) String() string { return proto.CompactTextString(m) }
func (*AssetIssuance) ProtoMessage()    {}
func (*AssetIssuance) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{8}
}
func (m *AssetIssuance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetIssuance.Unmarshal(m, b)
}
func (m *AssetIssuance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetIssuance.Marshal(b, m, deterministic)
}
func (dst *AssetIssuance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIssuance.Merge(dst, src)
}
func (m *AssetIssuance) XXX_Size() int {
	return xxx_messageInfo_AssetIssuance.Size(m)
}
func (m *AssetIssuance) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIssuance.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIssuance proto.InternalMessageInfo

func (m *AssetIssuance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssetIssuance) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AssetIssuance) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *AssetIssuance) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *AssetIssuance) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type AssetTransfer struct {
	Quantity             uint64   `protobuf:"varint,1,opt,name=quantity" json:"quantity,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetTransfer) Reset()         { *m = AssetTransfer{} }
func (m *AssetTransfer) String() string { return proto.CompactTextString(m) }
func (*AssetTransfer) ProtoMessage()    {}
func (*AssetTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{9}
}
func (m *AssetTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetTransfer.Unmarshal(m, b)
}
func (m *AssetTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetTransfer.Marshal(b, m, deterministic)
}
func (dst *AssetTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetTransfer.Merge(dst, src)
}
func (m *AssetTransfer) XXX_Size() int {
	return xxx_messageInfo_AssetTransfer.Size(m)
}
func (m *AssetTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_AssetTransfer proto.InternalMessageInfo

func (m *AssetTransfer) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *AssetTransfer) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type AskOrderPlacement struct {
	Asset                uint64   `protobuf:"varint,1,opt,name=asset" json:"asset,omitempty"`
	Quantity             uint64   `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskOrderPlacement) Reset()         { *m = AskOrderPlacement{} }
func (m *AskOrderPlacement) String() string { return proto.CompactTextString(m) }
func (*AskOrderPlacement) ProtoMessage()    {}
func (*AskOrderPlacement) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{10}
}
func (m *AskOrderPlacement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskOrderPlacement.Unmarshal(m, b)
}
func (m *AskOrderPlacement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskOrderPlacement.Marshal(b, m, deterministic)
}
func (dst *AskOrderPlacement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskOrderPlacement.Merge(dst, src)
}
func (m *AskOrderPlacement) XXX_Size() int {
	return xxx_messageInfo_AskOrderPlacement.Size(m)
}
func (m *AskOrderPlacement) XXX_DiscardUnknown() {
	xxx_messageInfo_AskOrderPlacement.DiscardUnknown(m)
}

var xxx_messageInfo_AskOrderPlacement proto.InternalMessageInfo

func (m *AskOrderPlacement) GetAsset() uint64 {
	if m != nil {
		return m.Asset
	}
	return 0
}

func (m *AskOrderPlacement) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *AskOrderPlacement) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AskOrderPlacement) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type BidOrderPlacement struct {
	Asset                uint64   `protobuf:"varint,1,opt,name=asset" json:"asset,omitempty"`
	Quantity             uint64   `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidOrderPlacement) Reset()         { *m = BidOrderPlacement{} }
func (m *BidOrderPlacement) String() string { return proto.CompactTextString(m) }
func (*BidOrderPlacement) ProtoMessage()    {}
func (*BidOrderPlacement) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{11}
}
func (m *BidOrderPlacement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidOrderPlacement.Unmarshal(m, b)
}
func (m *BidOrderPlacement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidOrderPlacement.Marshal(b, m, deterministic)
}
func (dst *BidOrderPlacement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidOrderPlacement.Merge(dst, src)
}
func (m *BidOrderPlacement) XXX_Size() int {
	return xxx_messageInfo_BidOrderPlacement.Size(m)
}
func (m *BidOrderPlacement) XXX_DiscardUnknown() {
	xxx_messageInfo_BidOrderPlacement.DiscardUnknown(m)
}

var xxx_messageInfo_BidOrderPlacement proto.InternalMessageInfo

func (m *BidOrderPlacement) GetAsset() uint64 {
	if m != nil {
		return m.Asset
	}
	return 0
}

func (m *BidOrderPlacement) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *BidOrderPlacement) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AskOrderCancellation struct {
	Order                uint64   `protobuf:"varint,1,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskOrderCancellation) Reset()         { *m = AskOrderCancellation{} }
func (m *AskOrderCancellation) String() string { return proto.CompactTextString(m) }
func (*AskOrderCancellation) ProtoMessage()    {}
func (*AskOrderCancellation) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{12}
}
func (m *AskOrderCancellation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskOrderCancellation.Unmarshal(m, b)
}
func (m *AskOrderCancellation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskOrderCancellation.Marshal(b, m, deterministic)
}
func (dst *AskOrderCancellation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskOrderCancellation.Merge(dst, src)
}
func (m *AskOrderCancellation) XXX_Size() int {
	return xxx_messageInfo_AskOrderCancellation.Size(m)
}
func (m *AskOrderCancellation) XXX_DiscardUnknown() {
	xxx_messageInfo_AskOrderCancellation.DiscardUnknown(m)
}

var xxx_messageInfo_AskOrderCancellation proto.InternalMessageInfo

func (m *AskOrderCancellation) GetOrder() uint64 {
	if m != nil {
		return m.Order
	}
	return 0
}

type BidOrderCancellation struct {
	Order                uint64   `protobuf:"varint,1,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidOrderCancellation) Reset()         { *m = BidOrderCancellation{} }
func (m *BidOrderCancellation) String() string { return proto.CompactTextString(m) }
func (*BidOrderCancellation) ProtoMessage()    {}
func (*BidOrderCancellation) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{13}
}
func (m *BidOrderCancellation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidOrderCancellation.Unmarshal(m, b)
}
func (m *BidOrderCancellation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidOrderCancellation.Marshal(b, m, deterministic)
}
func (dst *BidOrderCancellation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidOrderCancellation.Merge(dst, src)
}
func (m *BidOrderCancellation) XXX_Size() int {
	return xxx_messageInfo_BidOrderCancellation.Size(m)
}
func (m *BidOrderCancellation) XXX_DiscardUnknown() {
	xxx_messageInfo_BidOrderCancellation.DiscardUnknown(m)
}

var xxx_messageInfo_BidOrderCancellation proto.InternalMessageInfo

func (m *BidOrderCancellation) GetOrder() uint64 {
	if m != nil {
		return m.Order
	}
	return 0
}

type DigitalGoodsListing struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Tags                 string   `protobuf:"bytes,3,opt,name=tags" json:"tags,omitempty"`
	Quantity             uint32   `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"`
	Price                uint64   `protobuf:"varint,5,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsListing) Reset()         { *m = DigitalGoodsListing{} }
func (m *DigitalGoodsListing) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsListing) ProtoMessage()    {}
func (*DigitalGoodsListing) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{14}
}
func (m *DigitalGoodsListing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsListing.Unmarshal(m, b)
}
func (m *DigitalGoodsListing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsListing.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsListing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsListing.Merge(dst, src)
}
func (m *DigitalGoodsListing) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsListing.Size(m)
}
func (m *DigitalGoodsListing) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsListing.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsListing proto.InternalMessageInfo

func (m *DigitalGoodsListing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DigitalGoodsListing) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DigitalGoodsListing) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *DigitalGoodsListing) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *DigitalGoodsListing) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type DigitalGoodsDelisting struct {
	Goods                string   `protobuf:"bytes,1,opt,name=goods" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsDelisting) Reset()         { *m = DigitalGoodsDelisting{} }
func (m *DigitalGoodsDelisting) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsDelisting) ProtoMessage()    {}
func (*DigitalGoodsDelisting) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{15}
}
func (m *DigitalGoodsDelisting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsDelisting.Unmarshal(m, b)
}
func (m *DigitalGoodsDelisting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsDelisting.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsDelisting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsDelisting.Merge(dst, src)
}
func (m *DigitalGoodsDelisting) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsDelisting.Size(m)
}
func (m *DigitalGoodsDelisting) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsDelisting.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsDelisting proto.InternalMessageInfo

func (m *DigitalGoodsDelisting) GetGoods() string {
	if m != nil {
		return m.Goods
	}
	return ""
}

type DigitalGoodsPriceChange struct {
	Goods                uint64   `protobuf:"varint,1,opt,name=goods" json:"goods,omitempty"`
	Price                uint64   `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsPriceChange) Reset()         { *m = DigitalGoodsPriceChange{} }
func (m *DigitalGoodsPriceChange) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsPriceChange) ProtoMessage()    {}
func (*DigitalGoodsPriceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{16}
}
func (m *DigitalGoodsPriceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsPriceChange.Unmarshal(m, b)
}
func (m *DigitalGoodsPriceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsPriceChange.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsPriceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsPriceChange.Merge(dst, src)
}
func (m *DigitalGoodsPriceChange) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsPriceChange.Size(m)
}
func (m *DigitalGoodsPriceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsPriceChange.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsPriceChange proto.InternalMessageInfo

func (m *DigitalGoodsPriceChange) GetGoods() uint64 {
	if m != nil {
		return m.Goods
	}
	return 0
}

func (m *DigitalGoodsPriceChange) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type DigitalGoodsQuantityChange struct {
	Goods                uint64   `protobuf:"varint,1,opt,name=goods" json:"goods,omitempty"`
	DeltaQuantity        int32    `protobuf:"varint,2,opt,name=deltaQuantity" json:"deltaQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsQuantityChange) Reset()         { *m = DigitalGoodsQuantityChange{} }
func (m *DigitalGoodsQuantityChange) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsQuantityChange) ProtoMessage()    {}
func (*DigitalGoodsQuantityChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{17}
}
func (m *DigitalGoodsQuantityChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsQuantityChange.Unmarshal(m, b)
}
func (m *DigitalGoodsQuantityChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsQuantityChange.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsQuantityChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsQuantityChange.Merge(dst, src)
}
func (m *DigitalGoodsQuantityChange) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsQuantityChange.Size(m)
}
func (m *DigitalGoodsQuantityChange) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsQuantityChange.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsQuantityChange proto.InternalMessageInfo

func (m *DigitalGoodsQuantityChange) GetGoods() uint64 {
	if m != nil {
		return m.Goods
	}
	return 0
}

func (m *DigitalGoodsQuantityChange) GetDeltaQuantity() int32 {
	if m != nil {
		return m.DeltaQuantity
	}
	return 0
}

type DigitalGoodsPurchase struct {
	Goods                     uint64   `protobuf:"varint,1,opt,name=goods" json:"goods,omitempty"`
	Quantity                  uint32   `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	Price                     uint64   `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	DeliveryDeadlineTimestamp uint32   `protobuf:"varint,4,opt,name=deliveryDeadlineTimestamp" json:"deliveryDeadlineTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *DigitalGoodsPurchase) Reset()         { *m = DigitalGoodsPurchase{} }
func (m *DigitalGoodsPurchase) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsPurchase) ProtoMessage()    {}
func (*DigitalGoodsPurchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{18}
}
func (m *DigitalGoodsPurchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsPurchase.Unmarshal(m, b)
}
func (m *DigitalGoodsPurchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsPurchase.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsPurchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsPurchase.Merge(dst, src)
}
func (m *DigitalGoodsPurchase) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsPurchase.Size(m)
}
func (m *DigitalGoodsPurchase) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsPurchase.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsPurchase proto.InternalMessageInfo

func (m *DigitalGoodsPurchase) GetGoods() uint64 {
	if m != nil {
		return m.Goods
	}
	return 0
}

func (m *DigitalGoodsPurchase) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *DigitalGoodsPurchase) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DigitalGoodsPurchase) GetDeliveryDeadlineTimestamp() uint32 {
	if m != nil {
		return m.DeliveryDeadlineTimestamp
	}
	return 0
}

type DigitalGoodsDelivery struct {
	Purchase             uint64   `protobuf:"varint,1,opt,name=purchase" json:"purchase,omitempty"`
	GoodsIsText          bool     `protobuf:"varint,2,opt,name=goodsIsText" json:"goodsIsText,omitempty"`
	GoodsData            []byte   `protobuf:"bytes,3,opt,name=goodsData,proto3" json:"goodsData,omitempty"`
	GoodsNonce           []byte   `protobuf:"bytes,4,opt,name=goodsNonce,proto3" json:"goodsNonce,omitempty"`
	Discount             uint64   `protobuf:"varint,5,opt,name=discount" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsDelivery) Reset()         { *m = DigitalGoodsDelivery{} }
func (m *DigitalGoodsDelivery) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsDelivery) ProtoMessage()    {}
func (*DigitalGoodsDelivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{19}
}
func (m *DigitalGoodsDelivery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsDelivery.Unmarshal(m, b)
}
func (m *DigitalGoodsDelivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsDelivery.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsDelivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsDelivery.Merge(dst, src)
}
func (m *DigitalGoodsDelivery) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsDelivery.Size(m)
}
func (m *DigitalGoodsDelivery) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsDelivery.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsDelivery proto.InternalMessageInfo

func (m *DigitalGoodsDelivery) GetPurchase() uint64 {
	if m != nil {
		return m.Purchase
	}
	return 0
}

func (m *DigitalGoodsDelivery) GetGoodsIsText() bool {
	if m != nil {
		return m.GoodsIsText
	}
	return false
}

func (m *DigitalGoodsDelivery) GetGoodsData() []byte {
	if m != nil {
		return m.GoodsData
	}
	return nil
}

func (m *DigitalGoodsDelivery) GetGoodsNonce() []byte {
	if m != nil {
		return m.GoodsNonce
	}
	return nil
}

func (m *DigitalGoodsDelivery) GetDiscount() uint64 {
	if m != nil {
		return m.Discount
	}
	return 0
}

type DigitalGoodsFeedback struct {
	Purchase             uint64   `protobuf:"varint,1,opt,name=purchase" json:"purchase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsFeedback) Reset()         { *m = DigitalGoodsFeedback{} }
func (m *DigitalGoodsFeedback) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsFeedback) ProtoMessage()    {}
func (*DigitalGoodsFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{20}
}
func (m *DigitalGoodsFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsFeedback.Unmarshal(m, b)
}
func (m *DigitalGoodsFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsFeedback.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsFeedback.Merge(dst, src)
}
func (m *DigitalGoodsFeedback) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsFeedback.Size(m)
}
func (m *DigitalGoodsFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsFeedback proto.InternalMessageInfo

func (m *DigitalGoodsFeedback) GetPurchase() uint64 {
	if m != nil {
		return m.Purchase
	}
	return 0
}

type DigitalGoodsRefund struct {
	Purchase             uint64   `protobuf:"varint,1,opt,name=purchase" json:"purchase,omitempty"`
	RefundPrice          uint64   `protobuf:"varint,2,opt,name=refundPrice" json:"refundPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigitalGoodsRefund) Reset()         { *m = DigitalGoodsRefund{} }
func (m *DigitalGoodsRefund) String() string { return proto.CompactTextString(m) }
func (*DigitalGoodsRefund) ProtoMessage()    {}
func (*DigitalGoodsRefund) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{21}
}
func (m *DigitalGoodsRefund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigitalGoodsRefund.Unmarshal(m, b)
}
func (m *DigitalGoodsRefund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigitalGoodsRefund.Marshal(b, m, deterministic)
}
func (dst *DigitalGoodsRefund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigitalGoodsRefund.Merge(dst, src)
}
func (m *DigitalGoodsRefund) XXX_Size() int {
	return xxx_messageInfo_DigitalGoodsRefund.Size(m)
}
func (m *DigitalGoodsRefund) XXX_DiscardUnknown() {
	xxx_messageInfo_DigitalGoodsRefund.DiscardUnknown(m)
}

var xxx_messageInfo_DigitalGoodsRefund proto.InternalMessageInfo

func (m *DigitalGoodsRefund) GetPurchase() uint64 {
	if m != nil {
		return m.Purchase
	}
	return 0
}

func (m *DigitalGoodsRefund) GetRefundPrice() uint64 {
	if m != nil {
		return m.RefundPrice
	}
	return 0
}

type EffectiveBalanceLeasing struct {
	Period               uint32   `protobuf:"varint,1,opt,name=period" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EffectiveBalanceLeasing) Reset()         { *m = EffectiveBalanceLeasing{} }
func (m *EffectiveBalanceLeasing) String() string { return proto.CompactTextString(m) }
func (*EffectiveBalanceLeasing) ProtoMessage()    {}
func (*EffectiveBalanceLeasing) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{22}
}
func (m *EffectiveBalanceLeasing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EffectiveBalanceLeasing.Unmarshal(m, b)
}
func (m *EffectiveBalanceLeasing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EffectiveBalanceLeasing.Marshal(b, m, deterministic)
}
func (dst *EffectiveBalanceLeasing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EffectiveBalanceLeasing.Merge(dst, src)
}
func (m *EffectiveBalanceLeasing) XXX_Size() int {
	return xxx_messageInfo_EffectiveBalanceLeasing.Size(m)
}
func (m *EffectiveBalanceLeasing) XXX_DiscardUnknown() {
	xxx_messageInfo_EffectiveBalanceLeasing.DiscardUnknown(m)
}

var xxx_messageInfo_EffectiveBalanceLeasing proto.InternalMessageInfo

func (m *EffectiveBalanceLeasing) GetPeriod() uint32 {
	if m != nil {
		return m.Period
	}
	return 0
}

type RewardRecipientAssignment struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewardRecipientAssignment) Reset()         { *m = RewardRecipientAssignment{} }
func (m *RewardRecipientAssignment) String() string { return proto.CompactTextString(m) }
func (*RewardRecipientAssignment) ProtoMessage()    {}
func (*RewardRecipientAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{23}
}
func (m *RewardRecipientAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardRecipientAssignment.Unmarshal(m, b)
}
func (m *RewardRecipientAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardRecipientAssignment.Marshal(b, m, deterministic)
}
func (dst *RewardRecipientAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardRecipientAssignment.Merge(dst, src)
}
func (m *RewardRecipientAssignment) XXX_Size() int {
	return xxx_messageInfo_RewardRecipientAssignment.Size(m)
}
func (m *RewardRecipientAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardRecipientAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_RewardRecipientAssignment proto.InternalMessageInfo

type EscrowCreation struct {
	Amount               uint64                        `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	DeadlineAction       EscrowCreation_DeadlineAction `protobuf:"varint,2,opt,name=deadlineAction,enum=p2p.EscrowCreation_DeadlineAction" json:"deadlineAction,omitempty"`
	RequiredSigners      int32                         `protobuf:"varint,3,opt,name=requiredSigners" json:"requiredSigners,omitempty"`
	Signers              []uint64                      `protobuf:"varint,4,rep,packed,name=signers" json:"signers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EscrowCreation) Reset()         { *m = EscrowCreation{} }
func (m *EscrowCreation) String() string { return proto.CompactTextString(m) }
func (*EscrowCreation) ProtoMessage()    {}
func (*EscrowCreation) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{24}
}
func (m *EscrowCreation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EscrowCreation.Unmarshal(m, b)
}
func (m *EscrowCreation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EscrowCreation.Marshal(b, m, deterministic)
}
func (dst *EscrowCreation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowCreation.Merge(dst, src)
}
func (m *EscrowCreation) XXX_Size() int {
	return xxx_messageInfo_EscrowCreation.Size(m)
}
func (m *EscrowCreation) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowCreation.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowCreation proto.InternalMessageInfo

func (m *EscrowCreation) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EscrowCreation) GetDeadlineAction() EscrowCreation_DeadlineAction {
	if m != nil {
		return m.DeadlineAction
	}
	return EscrowCreation_UNDECIDED
}

func (m *EscrowCreation) GetRequiredSigners() int32 {
	if m != nil {
		return m.RequiredSigners
	}
	return 0
}

func (m *EscrowCreation) GetSigners() []uint64 {
	if m != nil {
		return m.Signers
	}
	return nil
}

type EscrowSign struct {
	EscrowID             uint64   `protobuf:"varint,1,opt,name=escrowID" json:"escrowID,omitempty"`
	Decision             uint32   `protobuf:"varint,2,opt,name=decision" json:"decision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EscrowSign) Reset()         { *m = EscrowSign{} }
func (m *EscrowSign) String() string { return proto.CompactTextString(m) }
func (*EscrowSign) ProtoMessage()    {}
func (*EscrowSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{25}
}
func (m *EscrowSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EscrowSign.Unmarshal(m, b)
}
func (m *EscrowSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EscrowSign.Marshal(b, m, deterministic)
}
func (dst *EscrowSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowSign.Merge(dst, src)
}
func (m *EscrowSign) XXX_Size() int {
	return xxx_messageInfo_EscrowSign.Size(m)
}
func (m *EscrowSign) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowSign.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowSign proto.InternalMessageInfo

func (m *EscrowSign) GetEscrowID() uint64 {
	if m != nil {
		return m.EscrowID
	}
	return 0
}

func (m *EscrowSign) GetDecision() uint32 {
	if m != nil {
		return m.Decision
	}
	return 0
}

type EscrowResult struct {
	EscrowID             uint64   `protobuf:"varint,1,opt,name=escrowID" json:"escrowID,omitempty"`
	Decision             uint32   `protobuf:"varint,2,opt,name=decision" json:"decision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EscrowResult) Reset()         { *m = EscrowResult{} }
func (m *EscrowResult) String() string { return proto.CompactTextString(m) }
func (*EscrowResult) ProtoMessage()    {}
func (*EscrowResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{26}
}
func (m *EscrowResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EscrowResult.Unmarshal(m, b)
}
func (m *EscrowResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EscrowResult.Marshal(b, m, deterministic)
}
func (dst *EscrowResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowResult.Merge(dst, src)
}
func (m *EscrowResult) XXX_Size() int {
	return xxx_messageInfo_EscrowResult.Size(m)
}
func (m *EscrowResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowResult.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowResult proto.InternalMessageInfo

func (m *EscrowResult) GetEscrowID() uint64 {
	if m != nil {
		return m.EscrowID
	}
	return 0
}

func (m *EscrowResult) GetDecision() uint32 {
	if m != nil {
		return m.Decision
	}
	return 0
}

type SubscriptionSubscribe struct {
	Frequency            uint32   `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionSubscribe) Reset()         { *m = SubscriptionSubscribe{} }
func (m *SubscriptionSubscribe) String() string { return proto.CompactTextString(m) }
func (*SubscriptionSubscribe) ProtoMessage()    {}
func (*SubscriptionSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{27}
}
func (m *SubscriptionSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionSubscribe.Unmarshal(m, b)
}
func (m *SubscriptionSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionSubscribe.Marshal(b, m, deterministic)
}
func (dst *SubscriptionSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionSubscribe.Merge(dst, src)
}
func (m *SubscriptionSubscribe) XXX_Size() int {
	return xxx_messageInfo_SubscriptionSubscribe.Size(m)
}
func (m *SubscriptionSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionSubscribe proto.InternalMessageInfo

func (m *SubscriptionSubscribe) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type SubscriptionCancel struct {
	SubscriptionID       uint64   `protobuf:"varint,1,opt,name=subscriptionID" json:"subscriptionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionCancel) Reset()         { *m = SubscriptionCancel{} }
func (m *SubscriptionCancel) String() string { return proto.CompactTextString(m) }
func (*SubscriptionCancel) ProtoMessage()    {}
func (*SubscriptionCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{28}
}
func (m *SubscriptionCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionCancel.Unmarshal(m, b)
}
func (m *SubscriptionCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionCancel.Marshal(b, m, deterministic)
}
func (dst *SubscriptionCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionCancel.Merge(dst, src)
}
func (m *SubscriptionCancel) XXX_Size() int {
	return xxx_messageInfo_SubscriptionCancel.Size(m)
}
func (m *SubscriptionCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionCancel.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionCancel proto.InternalMessageInfo

func (m *SubscriptionCancel) GetSubscriptionID() uint64 {
	if m != nil {
		return m.SubscriptionID
	}
	return 0
}

type SubscriptionPayment struct {
	SubscriptionID       []uint64 `protobuf:"varint,1,rep,packed,name=subscriptionID" json:"subscriptionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionPayment) Reset()         { *m = SubscriptionPayment{} }
func (m *SubscriptionPayment) String() string { return proto.CompactTextString(m) }
func (*SubscriptionPayment) ProtoMessage()    {}
func (*SubscriptionPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{29}
}
func (m *SubscriptionPayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionPayment.Unmarshal(m, b)
}
func (m *SubscriptionPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionPayment.Marshal(b, m, deterministic)
}
func (dst *SubscriptionPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionPayment.Merge(dst, src)
}
func (m *SubscriptionPayment) XXX_Size() int {
	return xxx_messageInfo_SubscriptionPayment.Size(m)
}
func (m *SubscriptionPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionPayment.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionPayment proto.InternalMessageInfo

func (m *SubscriptionPayment) GetSubscriptionID() []uint64 {
	if m != nil {
		return m.SubscriptionID
	}
	return nil
}

type AutomatedTransactionsCreation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	CreationBytes        []byte   `protobuf:"bytes,3,opt,name=creationBytes,proto3" json:"creationBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutomatedTransactionsCreation) Reset()         { *m = AutomatedTransactionsCreation{} }
func (m *AutomatedTransactionsCreation) String() string { return proto.CompactTextString(m) }
func (*AutomatedTransactionsCreation) ProtoMessage()    {}
func (*AutomatedTransactionsCreation) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{30}
}
func (m *AutomatedTransactionsCreation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutomatedTransactionsCreation.Unmarshal(m, b)
}
func (m *AutomatedTransactionsCreation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutomatedTransactionsCreation.Marshal(b, m, deterministic)
}
func (dst *AutomatedTransactionsCreation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutomatedTransactionsCreation.Merge(dst, src)
}
func (m *AutomatedTransactionsCreation) XXX_Size() int {
	return xxx_messageInfo_AutomatedTransactionsCreation.Size(m)
}
func (m *AutomatedTransactionsCreation) XXX_DiscardUnknown() {
	xxx_messageInfo_AutomatedTransactionsCreation.DiscardUnknown(m)
}

var xxx_messageInfo_AutomatedTransactionsCreation proto.InternalMessageInfo

func (m *AutomatedTransactionsCreation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AutomatedTransactionsCreation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AutomatedTransactionsCreation) GetCreationBytes() []byte {
	if m != nil {
		return m.CreationBytes
	}
	return nil
}

type EncryptedMessage struct {
	IsText               bool     `protobuf:"varint,1,opt,name=isText" json:"isText,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedMessage) Reset()         { *m = EncryptedMessage{} }
func (m *EncryptedMessage) String() string { return proto.CompactTextString(m) }
func (*EncryptedMessage) ProtoMessage()    {}
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{31}
}
func (m *EncryptedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedMessage.Unmarshal(m, b)
}
func (m *EncryptedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedMessage.Marshal(b, m, deterministic)
}
func (dst *EncryptedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedMessage.Merge(dst, src)
}
func (m *EncryptedMessage) XXX_Size() int {
	return xxx_messageInfo_EncryptedMessage.Size(m)
}
func (m *EncryptedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedMessage proto.InternalMessageInfo

func (m *EncryptedMessage) GetIsText() bool {
	if m != nil {
		return m.IsText
	}
	return false
}

func (m *EncryptedMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EncryptedMessage) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type EncryptedToSelfMessage struct {
	IsText               bool     `protobuf:"varint,1,opt,name=isText" json:"isText,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedToSelfMessage) Reset()         { *m = EncryptedToSelfMessage{} }
func (m *EncryptedToSelfMessage) String() string { return proto.CompactTextString(m) }
func (*EncryptedToSelfMessage) ProtoMessage()    {}
func (*EncryptedToSelfMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{32}
}
func (m *EncryptedToSelfMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedToSelfMessage.Unmarshal(m, b)
}
func (m *EncryptedToSelfMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedToSelfMessage.Marshal(b, m, deterministic)
}
func (dst *EncryptedToSelfMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedToSelfMessage.Merge(dst, src)
}
func (m *EncryptedToSelfMessage) XXX_Size() int {
	return xxx_messageInfo_EncryptedToSelfMessage.Size(m)
}
func (m *EncryptedToSelfMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedToSelfMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedToSelfMessage proto.InternalMessageInfo

func (m *EncryptedToSelfMessage) GetIsText() bool {
	if m != nil {
		return m.IsText
	}
	return false
}

func (m *EncryptedToSelfMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EncryptedToSelfMessage) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type PublicKeyAnnouncement struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyAnnouncement) Reset()         { *m = PublicKeyAnnouncement{} }
func (m *PublicKeyAnnouncement) String() string { return proto.CompactTextString(m) }
func (*PublicKeyAnnouncement) ProtoMessage()    {}
func (*PublicKeyAnnouncement) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_333c12f1df333022, []int{33}
}
func (m *PublicKeyAnnouncement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyAnnouncement.Unmarshal(m, b)
}
func (m *PublicKeyAnnouncement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyAnnouncement.Marshal(b, m, deterministic)
}
func (dst *PublicKeyAnnouncement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyAnnouncement.Merge(dst, src)
}
func (m *PublicKeyAnnouncement) XXX_Size() int {
	return xxx_messageInfo_PublicKeyAnnouncement.Size(m)
}
func (m *PublicKeyAnnouncement) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyAnnouncement.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyAnnouncement proto.InternalMessageInfo

func (m *PublicKeyAnnouncement) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Attachment)(nil), "p2p.Attachment")
	proto.RegisterType((*MultiOutCreation)(nil), "p2p.MultiOutCreation")
	proto.RegisterType((*MultiOutCreation_Recipients)(nil), "p2p.MultiOutCreation.Recipients")
	proto.RegisterType((*MultiSameOutCreation)(nil), "p2p.MultiSameOutCreation")
	proto.RegisterType((*ArbitaryMessage)(nil), "p2p.ArbitaryMessage")
	proto.RegisterType((*AliasAssignment)(nil), "p2p.AliasAssignment")
	proto.RegisterType((*AccountInfo)(nil), "p2p.AccountInfo")
	proto.RegisterType((*AliasSell)(nil), "p2p.AliasSell")
	proto.RegisterType((*AliasBuy)(nil), "p2p.AliasBuy")
	proto.RegisterType((*AssetIssuance)(nil), "p2p.AssetIssuance")
	proto.RegisterType((*AssetTransfer)(nil), "p2p.AssetTransfer")
	proto.RegisterType((*AskOrderPlacement)(nil), "p2p.AskOrderPlacement")
	proto.RegisterType((*BidOrderPlacement)(nil), "p2p.BidOrderPlacement")
	proto.RegisterType((*AskOrderCancellation)(nil), "p2p.AskOrderCancellation")
	proto.RegisterType((*BidOrderCancellation)(nil), "p2p.BidOrderCancellation")
	proto.RegisterType((*DigitalGoodsListing)(nil), "p2p.DigitalGoodsListing")
	proto.RegisterType((*DigitalGoodsDelisting)(nil), "p2p.DigitalGoodsDelisting")
	proto.RegisterType((*DigitalGoodsPriceChange)(nil), "p2p.DigitalGoodsPriceChange")
	proto.RegisterType((*DigitalGoodsQuantityChange)(nil), "p2p.DigitalGoodsQuantityChange")
	proto.RegisterType((*DigitalGoodsPurchase)(nil), "p2p.DigitalGoodsPurchase")
	proto.RegisterType((*DigitalGoodsDelivery)(nil), "p2p.DigitalGoodsDelivery")
	proto.RegisterType((*DigitalGoodsFeedback)(nil), "p2p.DigitalGoodsFeedback")
	proto.RegisterType((*DigitalGoodsRefund)(nil), "p2p.DigitalGoodsRefund")
	proto.RegisterType((*EffectiveBalanceLeasing)(nil), "p2p.EffectiveBalanceLeasing")
	proto.RegisterType((*RewardRecipientAssignment)(nil), "p2p.RewardRecipientAssignment")
	proto.RegisterType((*EscrowCreation)(nil), "p2p.EscrowCreation")
	proto.RegisterType((*EscrowSign)(nil), "p2p.EscrowSign")
	proto.RegisterType((*EscrowResult)(nil), "p2p.EscrowResult")
	proto.RegisterType((*SubscriptionSubscribe)(nil), "p2p.SubscriptionSubscribe")
	proto.RegisterType((*SubscriptionCancel)(nil), "p2p.SubscriptionCancel")
	proto.RegisterType((*SubscriptionPayment)(nil), "p2p.SubscriptionPayment")
	proto.RegisterType((*AutomatedTransactionsCreation)(nil), "p2p.AutomatedTransactionsCreation")
	proto.RegisterType((*EncryptedMessage)(nil), "p2p.EncryptedMessage")
	proto.RegisterType((*EncryptedToSelfMessage)(nil), "p2p.EncryptedToSelfMessage")
	proto.RegisterType((*PublicKeyAnnouncement)(nil), "p2p.PublicKeyAnnouncement")
	proto.RegisterEnum("p2p.EscrowCreation_DeadlineAction", EscrowCreation_DeadlineAction_name, EscrowCreation_DeadlineAction_value)
}

func init() { proto.RegisterFile("attachment.proto", fileDescriptor_attachment_333c12f1df333022) }

var fileDescriptor_attachment_333c12f1df333022 = []byte{
	// 1131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x8f, 0xdb, 0xc4,
	0x13, 0xff, 0x3a, 0x3f, 0xae, 0xcd, 0xdc, 0x25, 0x4d, 0xdd, 0xb4, 0x4d, 0xef, 0x5b, 0x50, 0xb4,
	0xaa, 0xd0, 0x3d, 0x40, 0x2a, 0x02, 0x05, 0x21, 0x15, 0x09, 0x5f, 0x9c, 0xa2, 0xc0, 0xb5, 0x4d,
	0x9d, 0x54, 0x42, 0xf0, 0xb4, 0xb1, 0x27, 0xe9, 0xaa, 0xce, 0xda, 0xf5, 0xae, 0x5b, 0x22, 0xfe,
	0x03, 0xde, 0x78, 0xe2, 0x85, 0xbf, 0x81, 0xff, 0x10, 0x09, 0xed, 0x7a, 0xed, 0xd8, 0x69, 0xaf,
	0x87, 0x4e, 0xf0, 0xe6, 0xcf, 0x78, 0xe6, 0x33, 0x9f, 0xdd, 0x9d, 0x9d, 0x59, 0xe8, 0x52, 0x29,
	0xa9, 0xff, 0x62, 0x83, 0x5c, 0x0e, 0xe3, 0x24, 0x92, 0x91, 0x5d, 0x8f, 0x47, 0xf1, 0xf1, 0x9d,
	0x75, 0x14, 0xad, 0x43, 0xbc, 0xaf, 0x4d, 0xcb, 0x74, 0x75, 0x9f, 0xf2, 0x6d, 0xf6, 0x9f, 0xcc,
	0x00, 0x9c, 0x22, 0xc6, 0xee, 0xc3, 0x95, 0xd7, 0x98, 0x08, 0x16, 0xf1, 0xbe, 0x35, 0xb0, 0x4e,
	0xda, 0x5e, 0x0e, 0xed, 0x13, 0x68, 0x04, 0x54, 0xd2, 0x7e, 0x6d, 0x60, 0x9d, 0x1c, 0x8e, 0x7a,
	0xc3, 0x8c, 0x71, 0x98, 0x33, 0x0e, 0x1d, 0xbe, 0xf5, 0xb4, 0x07, 0xf9, 0xd5, 0x82, 0xee, 0xe3,
	0x34, 0x94, 0xec, 0x69, 0x2a, 0xc7, 0x09, 0x52, 0xa9, 0xc2, 0xbf, 0x01, 0x48, 0xd0, 0x67, 0x31,
	0x43, 0x2e, 0x45, 0xdf, 0x1a, 0xd4, 0x4f, 0x0e, 0x47, 0x83, 0x61, 0x3c, 0x8a, 0x87, 0xfb, 0xae,
	0x43, 0xaf, 0xf0, 0xf3, 0x4a, 0x31, 0xc7, 0x9f, 0x03, 0xec, 0xfe, 0xd8, 0x1d, 0xa8, 0xb1, 0x40,
	0x6b, 0x6c, 0x78, 0x35, 0x16, 0xd8, 0xb7, 0xe0, 0x80, 0x6e, 0xa2, 0x94, 0x4b, 0x2d, 0xb0, 0xe1,
	0x19, 0x44, 0xbe, 0x80, 0x9e, 0x4e, 0x30, 0xa7, 0x1b, 0x2c, 0xeb, 0xf9, 0xf0, 0x2d, 0x3d, 0x8d,
	0x72, 0x36, 0x32, 0x86, 0x6b, 0x4e, 0xb2, 0x64, 0x92, 0x26, 0xdb, 0xc7, 0x28, 0x04, 0x5d, 0xa3,
	0x4a, 0xc1, 0xc4, 0x02, 0x7f, 0x96, 0x3a, 0xed, 0x55, 0xcf, 0x20, 0xb5, 0x67, 0x7e, 0xc4, 0x25,
	0x9a, 0xdc, 0x2d, 0x2f, 0x87, 0xe4, 0x2b, 0xb8, 0xe6, 0x84, 0x8c, 0x0a, 0x47, 0x08, 0xb6, 0xe6,
	0x7a, 0x83, 0x7b, 0xd0, 0xa4, 0xca, 0xa4, 0x39, 0x5a, 0x5e, 0x06, 0xec, 0x2e, 0xd4, 0xd3, 0x84,
	0x99, 0x70, 0xf5, 0x49, 0xc6, 0x70, 0xe8, 0xf8, 0xbe, 0x5a, 0xc2, 0x94, 0xaf, 0x22, 0xdb, 0x86,
	0x06, 0xa7, 0x1b, 0x34, 0x51, 0xfa, 0xdb, 0x1e, 0xc0, 0x61, 0x80, 0xc2, 0x4f, 0x58, 0xac, 0x56,
	0x64, 0x82, 0xcb, 0x26, 0xf2, 0x25, 0xb4, 0x74, 0xfe, 0x39, 0x86, 0xe1, 0x39, 0x99, 0x7b, 0xd0,
	0x8c, 0x13, 0xe6, 0xa3, 0x0e, 0xaf, 0x7b, 0x19, 0x20, 0x03, 0xb8, 0xaa, 0x03, 0x4f, 0xd3, 0xed,
	0xbb, 0xe3, 0xc8, 0xef, 0x16, 0xb4, 0x1d, 0x21, 0x50, 0x4e, 0x85, 0x48, 0x29, 0xf7, 0xf1, 0x72,
	0x12, 0xed, 0x63, 0xb8, 0xfa, 0x2a, 0xa5, 0x5c, 0x32, 0xb9, 0xed, 0xd7, 0xf5, 0xc9, 0x15, 0x58,
	0xfd, 0x0b, 0xd0, 0x67, 0x1b, 0x1a, 0x8a, 0x7e, 0x43, 0x57, 0x63, 0x81, 0xb3, 0x4d, 0xdf, 0xa8,
	0x2d, 0xed, 0x37, 0xf3, 0x4d, 0xd7, 0x90, 0x4c, 0x8c, 0xb0, 0x45, 0x42, 0xb9, 0x58, 0x61, 0x52,
	0x49, 0x61, 0xed, 0xa5, 0x28, 0xd1, 0xd4, 0xaa, 0x34, 0x29, 0x5c, 0x77, 0xc4, 0xcb, 0xa7, 0x49,
	0x80, 0xc9, 0x2c, 0xa4, 0x3e, 0x16, 0xa7, 0xa7, 0xb8, 0x0d, 0x4f, 0x06, 0x2a, 0x09, 0x6a, 0x7b,
	0x09, 0x8a, 0xfd, 0xcd, 0x16, 0x97, 0x81, 0x72, 0xda, 0x46, 0x35, 0xed, 0x4f, 0x70, 0xfd, 0x94,
	0x05, 0xff, 0x4d, 0x5a, 0xf2, 0x31, 0xf4, 0xf2, 0x35, 0x8d, 0xd5, 0x99, 0x85, 0x61, 0x76, 0x19,
	0x7a, 0xd0, 0x8c, 0x94, 0x31, 0xe7, 0xd7, 0x40, 0x79, 0xe7, 0x52, 0xfe, 0x81, 0xf7, 0x6f, 0x16,
	0xdc, 0x70, 0xd9, 0x9a, 0x49, 0x1a, 0x7e, 0x1b, 0x45, 0x81, 0x38, 0x63, 0x42, 0x32, 0xbe, 0xbe,
	0x64, 0x59, 0xd8, 0xd0, 0x90, 0x74, 0x2d, 0xb4, 0xfc, 0x96, 0xa7, 0xbf, 0x2b, 0xeb, 0x35, 0xe5,
	0xf0, 0xf6, 0x7a, 0x9b, 0xe5, 0xf5, 0x7e, 0x02, 0x37, 0xcb, 0x92, 0x5c, 0x0c, 0x8d, 0xa8, 0x1e,
	0x34, 0xd7, 0xca, 0x92, 0xd7, 0xb4, 0x06, 0x64, 0x02, 0xb7, 0xcb, 0xee, 0x33, 0xc5, 0x31, 0x7e,
	0x41, 0xf9, 0x1a, 0xab, 0x01, 0x0d, 0x13, 0x50, 0xbd, 0x3c, 0x45, 0xd6, 0x1f, 0xe0, 0xb8, 0x4c,
	0xf3, 0xcc, 0x68, 0x7c, 0x2f, 0xd3, 0x3d, 0x68, 0x07, 0x18, 0x4a, 0xfa, 0xac, 0x7c, 0xa0, 0x4d,
	0xaf, 0x6a, 0x24, 0x7f, 0x58, 0xd0, 0xab, 0x28, 0x4c, 0x13, 0xff, 0x05, 0x15, 0xe7, 0x91, 0xee,
	0x17, 0x48, 0xfb, 0xc2, 0xba, 0x7c, 0x08, 0x77, 0x02, 0x0c, 0xd9, 0x6b, 0x4c, 0xb6, 0x2e, 0xd2,
	0x20, 0x64, 0x1c, 0x17, 0x6c, 0x83, 0x42, 0xd2, 0x4d, 0x6c, 0xf6, 0xfc, 0x7c, 0x07, 0xf2, 0xe7,
	0x9e, 0x3c, 0xd7, 0x78, 0x2a, 0x21, 0xb1, 0x91, 0x9a, 0xdf, 0xc0, 0x1c, 0xab, 0x5a, 0xd0, 0x6a,
	0xa7, 0x59, 0x6b, 0xad, 0xe9, 0xd6, 0x5a, 0x36, 0xd9, 0x77, 0xa1, 0xa5, 0xa1, 0xab, 0xc6, 0x8f,
	0x92, 0x7b, 0xe4, 0xed, 0x0c, 0xaa, 0x91, 0x6b, 0xf0, 0x24, 0xe2, 0x3e, 0x6a, 0x8d, 0x47, 0x5e,
	0xc9, 0xa2, 0x9b, 0x08, 0x13, 0xba, 0x93, 0x9a, 0xe2, 0x28, 0x30, 0x19, 0x55, 0xf5, 0x3e, 0x42,
	0x0c, 0x96, 0xd4, 0x7f, 0xf9, 0x3e, 0xbd, 0xc4, 0x03, 0xbb, 0x1c, 0xe3, 0xe1, 0x2a, 0xe5, 0xc1,
	0x45, 0x2b, 0x4c, 0xb4, 0xd7, 0xac, 0x54, 0x2b, 0x65, 0x13, 0xf9, 0x14, 0x6e, 0x4f, 0x56, 0x2b,
	0xf4, 0x25, 0x7b, 0x8d, 0xa7, 0x34, 0x54, 0x97, 0xed, 0x0c, 0xa9, 0x50, 0x95, 0x7a, 0x0b, 0x0e,
	0x62, 0x4c, 0x58, 0x14, 0x98, 0x79, 0x6c, 0x10, 0xf9, 0x3f, 0xdc, 0xf1, 0xf0, 0x0d, 0x4d, 0x82,
	0x62, 0x26, 0xee, 0x86, 0x0c, 0xf9, 0xcb, 0x82, 0xce, 0x44, 0xf8, 0x49, 0xf4, 0xa6, 0x98, 0x77,
	0xbb, 0xf9, 0x68, 0x95, 0xe7, 0xa3, 0xfd, 0x1d, 0x74, 0x02, 0x73, 0x90, 0x8e, 0x5f, 0xdc, 0xc6,
	0xce, 0x88, 0xe8, 0xd9, 0x5c, 0x25, 0x19, 0xba, 0x15, 0x4f, 0x6f, 0x2f, 0xd2, 0x3e, 0x81, 0x6b,
	0x09, 0xbe, 0x4a, 0x59, 0x82, 0xc1, 0x9c, 0xad, 0x39, 0x26, 0xd9, 0xfd, 0x6d, 0x7a, 0xfb, 0x66,
	0xd5, 0xff, 0x84, 0xf1, 0x68, 0xe8, 0xd1, 0x9b, 0x43, 0x32, 0x86, 0x4e, 0x35, 0x8b, 0xdd, 0x86,
	0xd6, 0xf3, 0x27, 0xee, 0x64, 0x3c, 0x75, 0x27, 0x6e, 0xf7, 0x7f, 0xf6, 0x21, 0x5c, 0xf1, 0x26,
	0x67, 0x13, 0x67, 0x3e, 0xe9, 0x5a, 0x36, 0xc0, 0x81, 0x37, 0x79, 0xf4, 0xfc, 0x89, 0xdb, 0xad,
	0xd9, 0x2d, 0x68, 0xce, 0x67, 0x67, 0xd3, 0x45, 0xb7, 0x4e, 0x5c, 0x80, 0x4c, 0xb9, 0xca, 0xa7,
	0xce, 0x06, 0x35, 0x9a, 0xba, 0xf9, 0xd9, 0xe4, 0x38, 0x1f, 0x31, 0x22, 0x5f, 0xb8, 0x19, 0x31,
	0x0a, 0x93, 0x47, 0x70, 0x94, 0xb1, 0x78, 0x28, 0xd2, 0x50, 0x5e, 0x9a, 0xe7, 0x01, 0xdc, 0x9c,
	0xa7, 0xcb, 0xa2, 0xb7, 0x99, 0xef, 0x25, 0xaa, 0xc2, 0x5e, 0xa9, 0x9d, 0x41, 0xee, 0x6f, 0xcd,
	0xf1, 0xee, 0x0c, 0xe4, 0x21, 0xd8, 0xe5, 0xb0, 0xac, 0x05, 0xdb, 0x1f, 0x41, 0x47, 0x94, 0xac,
	0x85, 0x94, 0x3d, 0x2b, 0xf9, 0x1a, 0x6e, 0x94, 0xa3, 0x67, 0x74, 0xab, 0x27, 0xc9, 0xbb, 0xc2,
	0xeb, 0xef, 0x08, 0xff, 0x05, 0x3e, 0x70, 0x52, 0x19, 0x6d, 0xa8, 0xc4, 0x40, 0x0f, 0x52, 0xaa,
	0x0f, 0x43, 0x14, 0xf5, 0x74, 0xb9, 0xb6, 0x7e, 0x0f, 0xda, 0xbe, 0x61, 0x38, 0xdd, 0x4a, 0x14,
	0xe6, 0x3a, 0x57, 0x8d, 0x64, 0x01, 0xdd, 0x09, 0xf7, 0x93, 0x6d, 0x2c, 0x31, 0xb8, 0xe8, 0xf1,
	0x65, 0x97, 0x9e, 0xa5, 0x47, 0xd9, 0x03, 0x54, 0xf5, 0x36, 0xae, 0xbb, 0x41, 0xc6, 0x9e, 0x01,
	0xf2, 0x23, 0xdc, 0x2a, 0x58, 0x17, 0xd1, 0x1c, 0xc3, 0xd5, 0xbf, 0xc7, 0xfd, 0x00, 0x6e, 0xce,
	0xd2, 0x65, 0xc8, 0xfc, 0xef, 0x71, 0xeb, 0x70, 0x1e, 0xa5, 0xdc, 0x4c, 0xee, 0xbb, 0xd0, 0x8a,
	0xf3, 0x1f, 0x9a, 0xfd, 0xc8, 0xdb, 0x19, 0x96, 0x07, 0xfa, 0xf5, 0xfc, 0xd9, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xad, 0x03, 0xd4, 0x06, 0xb6, 0x0b, 0x00, 0x00,
}
