// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCumulativeDifficultyResponse struct {
	BlockchainHeight     int32    `protobuf:"varint,1,opt,name=blockchainHeight" json:"blockchainHeight,omitempty"`
	CumulativeDifficulty string   `protobuf:"bytes,2,opt,name=cumulativeDifficulty" json:"cumulativeDifficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCumulativeDifficultyResponse) Reset()         { *m = GetCumulativeDifficultyResponse{} }
func (m *GetCumulativeDifficultyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCumulativeDifficultyResponse) ProtoMessage()    {}
func (*GetCumulativeDifficultyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_9b5c10e722445c62, []int{0}
}
func (m *GetCumulativeDifficultyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Unmarshal(m, b)
}
func (m *GetCumulativeDifficultyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Marshal(b, m, deterministic)
}
func (dst *GetCumulativeDifficultyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCumulativeDifficultyResponse.Merge(dst, src)
}
func (m *GetCumulativeDifficultyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Size(m)
}
func (m *GetCumulativeDifficultyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCumulativeDifficultyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCumulativeDifficultyResponse proto.InternalMessageInfo

func (m *GetCumulativeDifficultyResponse) GetBlockchainHeight() int32 {
	if m != nil {
		return m.BlockchainHeight
	}
	return 0
}

func (m *GetCumulativeDifficultyResponse) GetCumulativeDifficulty() string {
	if m != nil {
		return m.CumulativeDifficulty
	}
	return ""
}

type GetNextBlocksResponse struct {
	NextBlocks           []*Block `protobuf:"bytes,1,rep,name=nextBlocks" json:"nextBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlocksResponse) Reset()         { *m = GetNextBlocksResponse{} }
func (m *GetNextBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlocksResponse) ProtoMessage()    {}
func (*GetNextBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_9b5c10e722445c62, []int{1}
}
func (m *GetNextBlocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlocksResponse.Unmarshal(m, b)
}
func (m *GetNextBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlocksResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlocksResponse.Merge(dst, src)
}
func (m *GetNextBlocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlocksResponse.Size(m)
}
func (m *GetNextBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlocksResponse proto.InternalMessageInfo

func (m *GetNextBlocksResponse) GetNextBlocks() []*Block {
	if m != nil {
		return m.NextBlocks
	}
	return nil
}

type GetNextBlockIdsResponse struct {
	NextBlockIds         []uint64 `protobuf:"varint,1,rep,packed,name=nextBlockIds" json:"nextBlockIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlockIdsResponse) Reset()         { *m = GetNextBlockIdsResponse{} }
func (m *GetNextBlockIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlockIdsResponse) ProtoMessage()    {}
func (*GetNextBlockIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_9b5c10e722445c62, []int{2}
}
func (m *GetNextBlockIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlockIdsResponse.Unmarshal(m, b)
}
func (m *GetNextBlockIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlockIdsResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlockIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlockIdsResponse.Merge(dst, src)
}
func (m *GetNextBlockIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlockIdsResponse.Size(m)
}
func (m *GetNextBlockIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlockIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlockIdsResponse proto.InternalMessageInfo

func (m *GetNextBlockIdsResponse) GetNextBlockIds() []uint64 {
	if m != nil {
		return m.NextBlockIds
	}
	return nil
}

type GetPeers struct {
	Peers                []string `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeers) Reset()         { *m = GetPeers{} }
func (m *GetPeers) String() string { return proto.CompactTextString(m) }
func (*GetPeers) ProtoMessage()    {}
func (*GetPeers) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_9b5c10e722445c62, []int{3}
}
func (m *GetPeers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeers.Unmarshal(m, b)
}
func (m *GetPeers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeers.Marshal(b, m, deterministic)
}
func (dst *GetPeers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeers.Merge(dst, src)
}
func (m *GetPeers) XXX_Size() int {
	return xxx_messageInfo_GetPeers.Size(m)
}
func (m *GetPeers) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeers.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeers proto.InternalMessageInfo

func (m *GetPeers) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Block struct {
	PayloadLength        uint32     `protobuf:"varint,1,opt,name=payloadLength" json:"payloadLength,omitempty"`
	TotalAmount          int64      `protobuf:"varint,2,opt,name=totalAmount" json:"totalAmount,omitempty"`
	GenerationSignature  []byte     `protobuf:"bytes,3,opt,name=generationSignature,proto3" json:"generationSignature,omitempty"`
	GeneratorPublicKey   []byte     `protobuf:"bytes,4,opt,name=generatorPublicKey,proto3" json:"generatorPublicKey,omitempty"`
	PayloadHash          []byte     `protobuf:"bytes,5,opt,name=payloadHash,proto3" json:"payloadHash,omitempty"`
	BlockSignature       []byte     `protobuf:"bytes,6,opt,name=blockSignature,proto3" json:"blockSignature,omitempty"`
	Transactions         []*any.Any `protobuf:"bytes,7,rep,name=transactions" json:"transactions,omitempty"`
	Version              int32      `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	Nonce                uint64     `protobuf:"varint,9,opt,name=nonce" json:"nonce,omitempty"`
	TotalFee             int64      `protobuf:"varint,10,opt,name=totalFee" json:"totalFee,omitempty"`
	BlockATs             []byte     `protobuf:"bytes,11,opt,name=blockATs,proto3" json:"blockATs,omitempty"`
	PreviousBlock        uint64     `protobuf:"varint,12,opt,name=previousBlock" json:"previousBlock,omitempty"`
	Timestamp            uint64     `protobuf:"varint,13,opt,name=timestamp" json:"timestamp,omitempty"`
	Id                   uint64     `protobuf:"varint,14,opt,name=id" json:"id,omitempty"`
	Height               int32      `protobuf:"varint,15,opt,name=height" json:"height,omitempty"`
	PreviousBlockHash    []byte     `protobuf:"bytes,16,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_9b5c10e722445c62, []int{4}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetPayloadLength() uint32 {
	if m != nil {
		return m.PayloadLength
	}
	return 0
}

func (m *Block) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *Block) GetGenerationSignature() []byte {
	if m != nil {
		return m.GenerationSignature
	}
	return nil
}

func (m *Block) GetGeneratorPublicKey() []byte {
	if m != nil {
		return m.GeneratorPublicKey
	}
	return nil
}

func (m *Block) GetPayloadHash() []byte {
	if m != nil {
		return m.PayloadHash
	}
	return nil
}

func (m *Block) GetBlockSignature() []byte {
	if m != nil {
		return m.BlockSignature
	}
	return nil
}

func (m *Block) GetTransactions() []*any.Any {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetTotalFee() int64 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *Block) GetBlockATs() []byte {
	if m != nil {
		return m.BlockATs
	}
	return nil
}

func (m *Block) GetPreviousBlock() uint64 {
	if m != nil {
		return m.PreviousBlock
	}
	return 0
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Block) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCumulativeDifficultyResponse)(nil), "p2p.GetCumulativeDifficultyResponse")
	proto.RegisterType((*GetNextBlocksResponse)(nil), "p2p.GetNextBlocksResponse")
	proto.RegisterType((*GetNextBlockIdsResponse)(nil), "p2p.GetNextBlockIdsResponse")
	proto.RegisterType((*GetPeers)(nil), "p2p.GetPeers")
	proto.RegisterType((*Block)(nil), "p2p.Block")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_p2p_9b5c10e722445c62) }

var fileDescriptor_p2p_9b5c10e722445c62 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdd, 0x8e, 0xd3, 0x3e,
	0x10, 0xc5, 0x95, 0x7e, 0x6d, 0x3b, 0xfd, 0xf8, 0xef, 0xfa, 0x5f, 0xc0, 0x54, 0x48, 0x44, 0x11,
	0x42, 0x15, 0x42, 0x59, 0x54, 0x6e, 0xb8, 0xe1, 0xa2, 0x2c, 0xa2, 0x8b, 0x40, 0x68, 0x65, 0x78,
	0x01, 0x37, 0x9d, 0xa6, 0x16, 0xa9, 0x1d, 0xc5, 0x4e, 0x45, 0x2f, 0x79, 0x2a, 0x5e, 0x0f, 0x65,
	0xd2, 0x6d, 0x13, 0xb6, 0x77, 0x9d, 0xdf, 0x99, 0x1e, 0x4f, 0xce, 0x0c, 0xf4, 0xd2, 0x59, 0x1a,
	0xa6, 0x99, 0x71, 0x86, 0x35, 0xd3, 0x59, 0x3a, 0x79, 0x1a, 0x1b, 0x13, 0x27, 0x78, 0x4d, 0x68,
	0x99, 0xaf, 0xaf, 0xa5, 0xde, 0x97, 0xfa, 0xe4, 0xca, 0x65, 0x52, 0x5b, 0x19, 0x39, 0x65, 0x74,
	0x89, 0x82, 0xdf, 0x1e, 0x3c, 0x5f, 0xa0, 0xbb, 0xc9, 0xb7, 0x79, 0x22, 0x9d, 0xda, 0xe1, 0x47,
	0xb5, 0x5e, 0xab, 0x28, 0x4f, 0xdc, 0x5e, 0xa0, 0x4d, 0x8d, 0xb6, 0xc8, 0x5e, 0xc1, 0xe5, 0x32,
	0x31, 0xd1, 0xcf, 0x68, 0x23, 0x95, 0xbe, 0x45, 0x15, 0x6f, 0x1c, 0xf7, 0x7c, 0x6f, 0xda, 0x16,
	0x0f, 0x38, 0x9b, 0xc1, 0x38, 0x3a, 0xe3, 0xc5, 0x1b, 0xbe, 0x37, 0xed, 0x89, 0xb3, 0x5a, 0x70,
	0x03, 0x8f, 0x16, 0xe8, 0xbe, 0xe1, 0x2f, 0xf7, 0xa1, 0xb0, 0xb3, 0x95, 0x87, 0x41, 0x1f, 0x29,
	0xf7, 0xfc, 0xe6, 0xb4, 0x3f, 0x83, 0xb0, 0xf8, 0x5e, 0x42, 0xa2, 0xa2, 0x06, 0xef, 0xe1, 0x49,
	0xd5, 0xe4, 0xf3, 0xea, 0x64, 0x13, 0xc0, 0x40, 0x57, 0x38, 0x19, 0xb5, 0x44, 0x8d, 0x05, 0x3e,
	0x74, 0x17, 0xe8, 0xee, 0x10, 0x33, 0xcb, 0xc6, 0xd0, 0x4e, 0x8b, 0x1f, 0xd4, 0xd8, 0x13, 0x65,
	0x11, 0xfc, 0x69, 0x41, 0x9b, 0xda, 0xd9, 0x0b, 0x18, 0xa6, 0x72, 0x9f, 0x18, 0xb9, 0xfa, 0x8a,
	0x3a, 0x76, 0x1b, 0x0a, 0x63, 0x28, 0xea, 0x90, 0xf9, 0xd0, 0x77, 0xc6, 0xc9, 0x64, 0xbe, 0x35,
	0xb9, 0x76, 0x14, 0x40, 0x53, 0x54, 0x11, 0x7b, 0x03, 0xff, 0xc7, 0xa8, 0x31, 0x93, 0xc5, 0x3e,
	0xbe, 0xab, 0x58, 0x4b, 0x97, 0x67, 0xc8, 0x9b, 0xbe, 0x37, 0x1d, 0x88, 0x73, 0x12, 0x0b, 0x81,
	0x1d, 0xb0, 0xc9, 0xee, 0xf2, 0x65, 0xa2, 0xa2, 0x2f, 0xb8, 0xe7, 0x2d, 0xfa, 0xc3, 0x19, 0xa5,
	0x98, 0xe1, 0x30, 0xd4, 0xad, 0xb4, 0x1b, 0xde, 0xa6, 0xc6, 0x2a, 0x62, 0x2f, 0x61, 0x44, 0x3b,
	0x3c, 0x3d, 0xdf, 0xa1, 0xa6, 0x7f, 0x28, 0x7b, 0x07, 0x83, 0xca, 0xf1, 0x58, 0x7e, 0x41, 0xcb,
	0x18, 0x87, 0xe5, 0xb1, 0x85, 0xf7, 0xc7, 0x16, 0xce, 0xf5, 0x5e, 0xd4, 0x3a, 0x19, 0x87, 0x8b,
	0x1d, 0x66, 0x56, 0x19, 0xcd, 0xbb, 0x74, 0x34, 0xf7, 0x65, 0x91, 0xb3, 0x36, 0x3a, 0x42, 0xde,
	0xf3, 0xbd, 0x69, 0x4b, 0x94, 0x05, 0x9b, 0x40, 0x97, 0x42, 0xfa, 0x84, 0xc8, 0x81, 0x42, 0x3b,
	0xd6, 0x85, 0x46, 0x73, 0xcd, 0x7f, 0x58, 0xde, 0xa7, 0x39, 0x8f, 0x35, 0x6d, 0x25, 0xc3, 0x9d,
	0x32, 0xb9, 0xa5, 0x35, 0xf1, 0x01, 0xb9, 0xd6, 0x21, 0x7b, 0x06, 0x3d, 0xa7, 0xb6, 0x68, 0x9d,
	0xdc, 0xa6, 0x7c, 0x48, 0x1d, 0x27, 0xc0, 0x46, 0xd0, 0x50, 0x2b, 0x3e, 0x22, 0xdc, 0x50, 0x2b,
	0xf6, 0x18, 0x3a, 0x9b, 0xf2, 0xde, 0xff, 0xa3, 0xd1, 0x0f, 0x15, 0x7b, 0x0d, 0x57, 0x35, 0x5b,
	0x4a, 0xf7, 0x92, 0x06, 0x7a, 0x28, 0x2c, 0x3b, 0x94, 0xce, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc6, 0x10, 0x2a, 0x10, 0xaa, 0x03, 0x00, 0x00,
}
