// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{0}
}
func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (dst *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(dst, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetCumulativeDifficultyResponse struct {
	BlockchainHeight     int32    `protobuf:"varint,1,opt,name=blockchainHeight,proto3" json:"blockchainHeight,omitempty"`
	CumulativeDifficulty string   `protobuf:"bytes,2,opt,name=cumulativeDifficulty,proto3" json:"cumulativeDifficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCumulativeDifficultyResponse) Reset()         { *m = GetCumulativeDifficultyResponse{} }
func (m *GetCumulativeDifficultyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCumulativeDifficultyResponse) ProtoMessage()    {}
func (*GetCumulativeDifficultyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{1}
}
func (m *GetCumulativeDifficultyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Unmarshal(m, b)
}
func (m *GetCumulativeDifficultyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Marshal(b, m, deterministic)
}
func (dst *GetCumulativeDifficultyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCumulativeDifficultyResponse.Merge(dst, src)
}
func (m *GetCumulativeDifficultyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Size(m)
}
func (m *GetCumulativeDifficultyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCumulativeDifficultyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCumulativeDifficultyResponse proto.InternalMessageInfo

func (m *GetCumulativeDifficultyResponse) GetBlockchainHeight() int32 {
	if m != nil {
		return m.BlockchainHeight
	}
	return 0
}

func (m *GetCumulativeDifficultyResponse) GetCumulativeDifficulty() string {
	if m != nil {
		return m.CumulativeDifficulty
	}
	return ""
}

type GetInfoResponse struct {
	AnnouncedAddress     string   `protobuf:"bytes,1,opt,name=announcedAddress,proto3" json:"announcedAddress,omitempty"`
	Application          string   `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Platform             string   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	ShareAddress         bool     `protobuf:"varint,5,opt,name=shareAddress,proto3" json:"shareAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{2}
}
func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(dst, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetAnnouncedAddress() string {
	if m != nil {
		return m.AnnouncedAddress
	}
	return ""
}

func (m *GetInfoResponse) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *GetInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetInfoResponse) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *GetInfoResponse) GetShareAddress() bool {
	if m != nil {
		return m.ShareAddress
	}
	return false
}

type GetNextBlocksResponse struct {
	NextBlocks           []*Block `protobuf:"bytes,1,rep,name=nextBlocks,proto3" json:"nextBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlocksResponse) Reset()         { *m = GetNextBlocksResponse{} }
func (m *GetNextBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlocksResponse) ProtoMessage()    {}
func (*GetNextBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{3}
}
func (m *GetNextBlocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlocksResponse.Unmarshal(m, b)
}
func (m *GetNextBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlocksResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlocksResponse.Merge(dst, src)
}
func (m *GetNextBlocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlocksResponse.Size(m)
}
func (m *GetNextBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlocksResponse proto.InternalMessageInfo

func (m *GetNextBlocksResponse) GetNextBlocks() []*Block {
	if m != nil {
		return m.NextBlocks
	}
	return nil
}

type GetNextBlockIdsResponse struct {
	NextBlockIds         []uint64 `protobuf:"varint,1,rep,packed,name=nextBlockIds,proto3" json:"nextBlockIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlockIdsResponse) Reset()         { *m = GetNextBlockIdsResponse{} }
func (m *GetNextBlockIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlockIdsResponse) ProtoMessage()    {}
func (*GetNextBlockIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{4}
}
func (m *GetNextBlockIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlockIdsResponse.Unmarshal(m, b)
}
func (m *GetNextBlockIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlockIdsResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlockIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlockIdsResponse.Merge(dst, src)
}
func (m *GetNextBlockIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlockIdsResponse.Size(m)
}
func (m *GetNextBlockIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlockIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlockIdsResponse proto.InternalMessageInfo

func (m *GetNextBlockIdsResponse) GetNextBlockIds() []uint64 {
	if m != nil {
		return m.NextBlockIds
	}
	return nil
}

type GetPeers struct {
	Peers                []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeers) Reset()         { *m = GetPeers{} }
func (m *GetPeers) String() string { return proto.CompactTextString(m) }
func (*GetPeers) ProtoMessage()    {}
func (*GetPeers) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{5}
}
func (m *GetPeers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeers.Unmarshal(m, b)
}
func (m *GetPeers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeers.Marshal(b, m, deterministic)
}
func (dst *GetPeers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeers.Merge(dst, src)
}
func (m *GetPeers) XXX_Size() int {
	return xxx_messageInfo_GetPeers.Size(m)
}
func (m *GetPeers) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeers.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeers proto.InternalMessageInfo

func (m *GetPeers) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Block struct {
	PayloadLength        uint32     `protobuf:"varint,1,opt,name=payloadLength,proto3" json:"payloadLength,omitempty"`
	TotalAmount          int64      `protobuf:"varint,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	GenerationSignature  []byte     `protobuf:"bytes,3,opt,name=generationSignature,proto3" json:"generationSignature,omitempty"`
	GeneratorPublicKey   []byte     `protobuf:"bytes,4,opt,name=generatorPublicKey,proto3" json:"generatorPublicKey,omitempty"`
	PayloadHash          []byte     `protobuf:"bytes,5,opt,name=payloadHash,proto3" json:"payloadHash,omitempty"`
	BlockSignature       []byte     `protobuf:"bytes,6,opt,name=blockSignature,proto3" json:"blockSignature,omitempty"`
	Transactions         []*any.Any `protobuf:"bytes,7,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Version              int32      `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Nonce                uint64     `protobuf:"varint,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TotalFee             int64      `protobuf:"varint,10,opt,name=totalFee,proto3" json:"totalFee,omitempty"`
	BlockATs             []byte     `protobuf:"bytes,11,opt,name=blockATs,proto3" json:"blockATs,omitempty"`
	PreviousBlock        uint64     `protobuf:"varint,12,opt,name=previousBlock,proto3" json:"previousBlock,omitempty"`
	Timestamp            uint32     `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   uint64     `protobuf:"varint,14,opt,name=id,proto3" json:"id,omitempty"`
	Height               int32      `protobuf:"varint,15,opt,name=height,proto3" json:"height,omitempty"`
	PreviousBlockHash    []byte     `protobuf:"bytes,16,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
	BaseTarget           uint64     `protobuf:"varint,17,opt,name=baseTarget,proto3" json:"baseTarget,omitempty"`
	CumulativeDifficulty []byte     `protobuf:"bytes,18,opt,name=cumulativeDifficulty,proto3" json:"cumulativeDifficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_bd08efa921e356d7, []int{6}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetPayloadLength() uint32 {
	if m != nil {
		return m.PayloadLength
	}
	return 0
}

func (m *Block) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *Block) GetGenerationSignature() []byte {
	if m != nil {
		return m.GenerationSignature
	}
	return nil
}

func (m *Block) GetGeneratorPublicKey() []byte {
	if m != nil {
		return m.GeneratorPublicKey
	}
	return nil
}

func (m *Block) GetPayloadHash() []byte {
	if m != nil {
		return m.PayloadHash
	}
	return nil
}

func (m *Block) GetBlockSignature() []byte {
	if m != nil {
		return m.BlockSignature
	}
	return nil
}

func (m *Block) GetTransactions() []*any.Any {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetTotalFee() int64 {
	if m != nil {
		return m.TotalFee
	}
	return 0
}

func (m *Block) GetBlockATs() []byte {
	if m != nil {
		return m.BlockATs
	}
	return nil
}

func (m *Block) GetPreviousBlock() uint64 {
	if m != nil {
		return m.PreviousBlock
	}
	return 0
}

func (m *Block) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Block) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func (m *Block) GetBaseTarget() uint64 {
	if m != nil {
		return m.BaseTarget
	}
	return 0
}

func (m *Block) GetCumulativeDifficulty() []byte {
	if m != nil {
		return m.CumulativeDifficulty
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "p2p.ErrorResponse")
	proto.RegisterType((*GetCumulativeDifficultyResponse)(nil), "p2p.GetCumulativeDifficultyResponse")
	proto.RegisterType((*GetInfoResponse)(nil), "p2p.GetInfoResponse")
	proto.RegisterType((*GetNextBlocksResponse)(nil), "p2p.GetNextBlocksResponse")
	proto.RegisterType((*GetNextBlockIdsResponse)(nil), "p2p.GetNextBlockIdsResponse")
	proto.RegisterType((*GetPeers)(nil), "p2p.GetPeers")
	proto.RegisterType((*Block)(nil), "p2p.Block")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_p2p_bd08efa921e356d7) }

var fileDescriptor_p2p_bd08efa921e356d7 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0xe5, 0xa6, 0x69, 0x93, 0xa9, 0xd3, 0x3f, 0xfb, 0xe6, 0x85, 0xa5, 0x42, 0x10, 0x59,
	0x80, 0x22, 0x84, 0x52, 0x14, 0x2e, 0x5c, 0x38, 0x84, 0x02, 0x69, 0x05, 0x42, 0xd5, 0xd2, 0x2f,
	0xb0, 0xb1, 0x27, 0xce, 0x0a, 0x67, 0xd7, 0xda, 0x5d, 0x57, 0xe4, 0xc8, 0x99, 0x4f, 0xc4, 0xb7,
	0x43, 0x1e, 0xa7, 0xa9, 0x4d, 0xc3, 0x2d, 0xf3, 0x7b, 0x36, 0x33, 0xe3, 0x67, 0x66, 0xa0, 0x9b,
	0x8f, 0xf3, 0x51, 0x6e, 0x8d, 0x37, 0xac, 0x95, 0x8f, 0xf3, 0xd3, 0x47, 0xa9, 0x31, 0x69, 0x86,
	0x67, 0x84, 0x66, 0xc5, 0xfc, 0x4c, 0xea, 0x55, 0xa5, 0x9f, 0x9e, 0x78, 0x2b, 0xb5, 0x93, 0xb1,
	0x57, 0x46, 0x57, 0x28, 0x7a, 0x0e, 0xbd, 0x8f, 0xd6, 0x1a, 0x2b, 0xd0, 0xe5, 0x46, 0x3b, 0x64,
	0x7d, 0x68, 0x63, 0x09, 0x78, 0x30, 0x08, 0x86, 0x5d, 0x51, 0x05, 0xd1, 0xcf, 0x00, 0x9e, 0x4e,
	0xd1, 0x9f, 0x17, 0xcb, 0x22, 0x93, 0x5e, 0xdd, 0xe0, 0x07, 0x35, 0x9f, 0xab, 0xb8, 0xc8, 0xfc,
	0x6a, 0xf3, 0xcf, 0x97, 0x70, 0x3c, 0xcb, 0x4c, 0xfc, 0x3d, 0x5e, 0x48, 0xa5, 0x2f, 0x50, 0xa5,
	0x0b, 0x4f, 0x49, 0xda, 0xe2, 0x1e, 0x67, 0x63, 0xe8, 0xc7, 0x5b, 0x72, 0xf1, 0x1d, 0x2a, 0xba,
	0x55, 0x8b, 0x7e, 0x07, 0x70, 0x34, 0x45, 0x7f, 0xa9, 0xe7, 0xa6, 0x5e, 0x53, 0x6a, 0x6d, 0x0a,
	0x1d, 0x63, 0x32, 0x49, 0x12, 0x8b, 0xce, 0xad, 0x1b, 0xbf, 0xc7, 0xd9, 0x00, 0x0e, 0x64, 0x9e,
	0x67, 0x2a, 0x96, 0xe5, 0xf7, 0xaf, 0x4b, 0xd5, 0x11, 0xe3, 0xb0, 0x7f, 0x83, 0xd6, 0x95, 0x6a,
	0x8b, 0xd4, 0xdb, 0x90, 0x9d, 0x42, 0x27, 0xcf, 0xa4, 0x9f, 0x1b, 0xbb, 0xe4, 0xbb, 0x24, 0x6d,
	0x62, 0x16, 0x41, 0xe8, 0x16, 0xd2, 0xe2, 0x6d, 0xfd, 0xf6, 0x20, 0x18, 0x76, 0x44, 0x83, 0x45,
	0xe7, 0xf0, 0xff, 0x14, 0xfd, 0x57, 0xfc, 0xe1, 0xdf, 0x97, 0x56, 0xb8, 0xda, 0x07, 0x80, 0xde,
	0x50, 0x1e, 0x0c, 0x5a, 0xc3, 0x83, 0x31, 0x8c, 0xca, 0x91, 0x12, 0x12, 0x35, 0x35, 0x7a, 0x07,
	0x0f, 0xeb, 0x49, 0x2e, 0x93, 0xbb, 0x34, 0x11, 0x84, 0xba, 0xc6, 0x29, 0xd1, 0xae, 0x68, 0xb0,
	0x68, 0x00, 0x9d, 0x29, 0xfa, 0x2b, 0x44, 0xeb, 0xca, 0x29, 0xe7, 0xe5, 0x0f, 0x7a, 0xd8, 0x15,
	0x55, 0x10, 0xfd, 0x6a, 0x43, 0x9b, 0x9e, 0xb3, 0x67, 0xd0, 0xcb, 0xe5, 0x2a, 0x33, 0x32, 0xf9,
	0x82, 0x3a, 0xf5, 0x0b, 0x32, 0xb5, 0x27, 0x9a, 0xb0, 0x74, 0xd4, 0x1b, 0x2f, 0xb3, 0xc9, 0xd2,
	0x14, 0xda, 0x93, 0xa3, 0x2d, 0x51, 0x47, 0xec, 0x35, 0xfc, 0x97, 0xa2, 0x46, 0x4b, 0xfe, 0x7e,
	0x53, 0xa9, 0x96, 0xbe, 0xb0, 0x48, 0xee, 0x86, 0x62, 0x9b, 0xc4, 0x46, 0xc0, 0xd6, 0xd8, 0xd8,
	0xab, 0x62, 0x96, 0xa9, 0xf8, 0x33, 0xae, 0xc8, 0xf3, 0x50, 0x6c, 0x51, 0xca, 0x1e, 0xd6, 0x4d,
	0x5d, 0x48, 0xb7, 0x20, 0xf3, 0x43, 0x51, 0x47, 0xec, 0x05, 0x1c, 0xd2, 0xfe, 0xdd, 0x95, 0xdf,
	0xa3, 0x47, 0x7f, 0x51, 0xf6, 0x16, 0xc2, 0xda, 0x7d, 0x38, 0xbe, 0x4f, 0xc3, 0xe8, 0x8f, 0xaa,
	0x7b, 0x1a, 0xdd, 0xde, 0xd3, 0x68, 0xa2, 0x57, 0xa2, 0xf1, 0xb2, 0xbe, 0x37, 0x1d, 0x5a, 0xf8,
	0xcd, 0xde, 0xf4, 0xa1, 0xad, 0x8d, 0x8e, 0x91, 0x77, 0x07, 0xc1, 0x70, 0x57, 0x54, 0x41, 0xb9,
	0x4d, 0x64, 0xd2, 0x27, 0x44, 0x0e, 0x64, 0xda, 0x26, 0x2e, 0x35, 0xea, 0x6b, 0x72, 0xed, 0xf8,
	0x01, 0xf5, 0xb9, 0x89, 0x69, 0x2a, 0x16, 0x6f, 0x94, 0x29, 0x1c, 0x8d, 0x89, 0x87, 0x94, 0xb5,
	0x09, 0xd9, 0x63, 0xe8, 0x7a, 0xb5, 0x44, 0xe7, 0xe5, 0x32, 0xe7, 0x3d, 0x9a, 0xdb, 0x1d, 0x60,
	0x87, 0xb0, 0xa3, 0x12, 0x7e, 0x48, 0x7f, 0xdc, 0x51, 0x09, 0x7b, 0x00, 0x7b, 0x8b, 0xea, 0x56,
	0x8f, 0xa8, 0xf5, 0x75, 0xc4, 0x5e, 0xc1, 0x49, 0x23, 0x2d, 0xb9, 0x7b, 0x4c, 0x0d, 0xdd, 0x17,
	0xd8, 0x13, 0x80, 0x99, 0x74, 0x78, 0x2d, 0x6d, 0x8a, 0x9e, 0x9f, 0x50, 0xf6, 0x1a, 0xf9, 0xe7,
	0xbd, 0x33, 0x4a, 0xb8, 0x55, 0x9b, 0xed, 0x91, 0xe3, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0xcf, 0x60, 0xb6, 0xe1, 0x04, 0x00, 0x00,
}
