// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RewardRecipient      uint64   `protobuf:"varint,2,opt,name=rewardRecipient,proto3" json:"rewardRecipient,omitempty"`
	Balance              int64    `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Reserved             int64    `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_e2fc3f7944d23f98, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetRewardRecipient() uint64 {
	if m != nil {
		return m.RewardRecipient
	}
	return 0
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetReserved() int64 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *Account) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "pb.Account")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_e2fc3f7944d23f98) }

var fileDescriptor_account_e2fc3f7944d23f98 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x3d, 0x8a, 0xc3, 0x30,
	0x10, 0x46, 0x91, 0xec, 0xb5, 0xd7, 0xc3, 0xfe, 0xc0, 0x54, 0xc3, 0xb2, 0x85, 0xd8, 0x4a, 0xd5,
	0x36, 0x7b, 0x82, 0xad, 0xd3, 0xe9, 0x06, 0xfa, 0x99, 0x42, 0xe0, 0xc8, 0x42, 0xb6, 0x13, 0x72,
	0xc0, 0xdc, 0x2b, 0x44, 0xc1, 0x09, 0xa4, 0x9b, 0xf7, 0x5e, 0x31, 0x7c, 0xf0, 0x6e, 0xbd, 0x9f,
	0xd6, 0xb4, 0xfc, 0xe6, 0x32, 0x2d, 0x13, 0xca, 0xec, 0x7e, 0xce, 0x02, 0xfa, 0xff, 0x9b, 0xc5,
	0x0f, 0x90, 0x31, 0x90, 0x50, 0x42, 0xb7, 0x46, 0xc6, 0x80, 0x1a, 0x3e, 0x0b, 0x1f, 0x6d, 0x09,
	0x86, 0x7d, 0xcc, 0x91, 0xd3, 0x42, 0xb2, 0xc6, 0x67, 0x8d, 0x04, 0xbd, 0xb3, 0xa3, 0x4d, 0x9e,
	0xa9, 0x51, 0x42, 0x37, 0x66, 0x43, 0xfc, 0x82, 0xd7, 0xc2, 0x33, 0x97, 0x03, 0x07, 0x6a, 0x6b,
	0xba, 0x33, 0x7e, 0xc3, 0x90, 0x57, 0x37, 0x46, 0xbf, 0xe3, 0x13, 0xbd, 0x28, 0xa1, 0xdf, 0xcc,
	0x43, 0x20, 0x42, 0x9b, 0xec, 0x9e, 0xa9, 0x53, 0x42, 0x0f, 0xa6, 0xde, 0xd7, 0x3f, 0x36, 0x84,
	0xc2, 0xf3, 0x4c, 0x7d, 0xd5, 0x1b, 0xba, 0xae, 0x4e, 0xfa, 0xbb, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x0f, 0xae, 0x5c, 0xe3, 0x00, 0x00, 0x00,
}
