// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCumulativeDifficultyResponse struct {
	BlockchainHeight     int32    `protobuf:"varint,1,opt,name=blockchainHeight" json:"blockchainHeight,omitempty"`
	CumulativeDifficulty string   `protobuf:"bytes,2,opt,name=cumulativeDifficulty" json:"cumulativeDifficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCumulativeDifficultyResponse) Reset()         { *m = GetCumulativeDifficultyResponse{} }
func (m *GetCumulativeDifficultyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCumulativeDifficultyResponse) ProtoMessage()    {}
func (*GetCumulativeDifficultyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_519f42562c38e535, []int{0}
}
func (m *GetCumulativeDifficultyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Unmarshal(m, b)
}
func (m *GetCumulativeDifficultyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Marshal(b, m, deterministic)
}
func (dst *GetCumulativeDifficultyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCumulativeDifficultyResponse.Merge(dst, src)
}
func (m *GetCumulativeDifficultyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Size(m)
}
func (m *GetCumulativeDifficultyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCumulativeDifficultyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCumulativeDifficultyResponse proto.InternalMessageInfo

func (m *GetCumulativeDifficultyResponse) GetBlockchainHeight() int32 {
	if m != nil {
		return m.BlockchainHeight
	}
	return 0
}

func (m *GetCumulativeDifficultyResponse) GetCumulativeDifficulty() string {
	if m != nil {
		return m.CumulativeDifficulty
	}
	return ""
}

type GetNextBlocksResponse struct {
	NextBlocks           []*Block `protobuf:"bytes,1,rep,name=nextBlocks" json:"nextBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlocksResponse) Reset()         { *m = GetNextBlocksResponse{} }
func (m *GetNextBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlocksResponse) ProtoMessage()    {}
func (*GetNextBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_519f42562c38e535, []int{1}
}
func (m *GetNextBlocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlocksResponse.Unmarshal(m, b)
}
func (m *GetNextBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlocksResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlocksResponse.Merge(dst, src)
}
func (m *GetNextBlocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlocksResponse.Size(m)
}
func (m *GetNextBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlocksResponse proto.InternalMessageInfo

func (m *GetNextBlocksResponse) GetNextBlocks() []*Block {
	if m != nil {
		return m.NextBlocks
	}
	return nil
}

type GetNextBlockIdsResponse struct {
	NextBlockIds         []uint64 `protobuf:"varint,1,rep,packed,name=nextBlockIds" json:"nextBlockIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlockIdsResponse) Reset()         { *m = GetNextBlockIdsResponse{} }
func (m *GetNextBlockIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlockIdsResponse) ProtoMessage()    {}
func (*GetNextBlockIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_519f42562c38e535, []int{2}
}
func (m *GetNextBlockIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlockIdsResponse.Unmarshal(m, b)
}
func (m *GetNextBlockIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlockIdsResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlockIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlockIdsResponse.Merge(dst, src)
}
func (m *GetNextBlockIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlockIdsResponse.Size(m)
}
func (m *GetNextBlockIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlockIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlockIdsResponse proto.InternalMessageInfo

func (m *GetNextBlockIdsResponse) GetNextBlockIds() []uint64 {
	if m != nil {
		return m.NextBlockIds
	}
	return nil
}

type GetPeers struct {
	Peers                []string `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeers) Reset()         { *m = GetPeers{} }
func (m *GetPeers) String() string { return proto.CompactTextString(m) }
func (*GetPeers) ProtoMessage()    {}
func (*GetPeers) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_519f42562c38e535, []int{3}
}
func (m *GetPeers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeers.Unmarshal(m, b)
}
func (m *GetPeers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeers.Marshal(b, m, deterministic)
}
func (dst *GetPeers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeers.Merge(dst, src)
}
func (m *GetPeers) XXX_Size() int {
	return xxx_messageInfo_GetPeers.Size(m)
}
func (m *GetPeers) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeers.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeers proto.InternalMessageInfo

func (m *GetPeers) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Block struct {
	PayloadLength        int64          `protobuf:"varint,1,opt,name=payloadLength" json:"payloadLength,omitempty"`
	TotalAmountNQT       int64          `protobuf:"varint,2,opt,name=totalAmountNQT" json:"totalAmountNQT,omitempty"`
	GenerationSignature  string         `protobuf:"bytes,3,opt,name=generationSignature" json:"generationSignature,omitempty"`
	GeneratorPublicKey   string         `protobuf:"bytes,4,opt,name=generatorPublicKey" json:"generatorPublicKey,omitempty"`
	PayloadHash          string         `protobuf:"bytes,5,opt,name=payloadHash" json:"payloadHash,omitempty"`
	BlockSignature       string         `protobuf:"bytes,6,opt,name=blockSignature" json:"blockSignature,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,7,rep,name=transactions" json:"transactions,omitempty"`
	Version              int32          `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	Nonce                string         `protobuf:"bytes,9,opt,name=nonce" json:"nonce,omitempty"`
	TotalFeeNQT          int64          `protobuf:"varint,10,opt,name=totalFeeNQT" json:"totalFeeNQT,omitempty"`
	BlockATs             []string       `protobuf:"bytes,11,rep,name=blockATs" json:"blockATs,omitempty"`
	PreviousBlock        uint64         `protobuf:"varint,12,opt,name=previousBlock" json:"previousBlock,omitempty"`
	Timestamp            int64          `protobuf:"varint,13,opt,name=timestamp" json:"timestamp,omitempty"`
	Block                uint64         `protobuf:"varint,14,opt,name=block" json:"block,omitempty"`
	Height               int32          `protobuf:"varint,15,opt,name=height" json:"height,omitempty"`
	PreviousBlockHash    string         `protobuf:"bytes,16,opt,name=previousBlockHash" json:"previousBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_519f42562c38e535, []int{4}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetPayloadLength() int64 {
	if m != nil {
		return m.PayloadLength
	}
	return 0
}

func (m *Block) GetTotalAmountNQT() int64 {
	if m != nil {
		return m.TotalAmountNQT
	}
	return 0
}

func (m *Block) GetGenerationSignature() string {
	if m != nil {
		return m.GenerationSignature
	}
	return ""
}

func (m *Block) GetGeneratorPublicKey() string {
	if m != nil {
		return m.GeneratorPublicKey
	}
	return ""
}

func (m *Block) GetPayloadHash() string {
	if m != nil {
		return m.PayloadHash
	}
	return ""
}

func (m *Block) GetBlockSignature() string {
	if m != nil {
		return m.BlockSignature
	}
	return ""
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Block) GetTotalFeeNQT() int64 {
	if m != nil {
		return m.TotalFeeNQT
	}
	return 0
}

func (m *Block) GetBlockATs() []string {
	if m != nil {
		return m.BlockATs
	}
	return nil
}

func (m *Block) GetPreviousBlock() uint64 {
	if m != nil {
		return m.PreviousBlock
	}
	return 0
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *Block) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetPreviousBlockHash() string {
	if m != nil {
		return m.PreviousBlockHash
	}
	return ""
}

type Transaction struct {
	SenderPublicKey string `protobuf:"bytes,1,opt,name=senderPublicKey" json:"senderPublicKey,omitempty"`
	Signature       string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	FeeNQT          int64  `protobuf:"varint,3,opt,name=feeNQT" json:"feeNQT,omitempty"`
	Type            int32  `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	Confirmations   int32  `protobuf:"varint,5,opt,name=confirmations" json:"confirmations,omitempty"`
	FullHash        string `protobuf:"bytes,6,opt,name=fullHash" json:"fullHash,omitempty"`
	Version         int32  `protobuf:"varint,7,opt,name=version" json:"version,omitempty"`
	EcBlockId       uint64 `protobuf:"varint,8,opt,name=ecBlockId" json:"ecBlockId,omitempty"`
	SignatureHash   string `protobuf:"bytes,9,opt,name=signatureHash" json:"signatureHash,omitempty"`
	// string attachment = 10; // ToDo
	SenderRS             string   `protobuf:"bytes,11,opt,name=senderRS" json:"senderRS,omitempty"`
	Subtype              int32    `protobuf:"varint,12,opt,name=subtype" json:"subtype,omitempty"`
	AmountNQT            int64    `protobuf:"varint,13,opt,name=amountNQT" json:"amountNQT,omitempty"`
	Sender               uint64   `protobuf:"varint,14,opt,name=sender" json:"sender,omitempty"`
	EcBlockHeight        int32    `protobuf:"varint,15,opt,name=ecBlockHeight" json:"ecBlockHeight,omitempty"`
	Block                uint64   `protobuf:"varint,16,opt,name=block" json:"block,omitempty"`
	BlockTimestamp       int64    `protobuf:"varint,17,opt,name=blockTimestamp" json:"blockTimestamp,omitempty"`
	Deadline             int32    `protobuf:"varint,18,opt,name=deadline" json:"deadline,omitempty"`
	Transaction          uint64   `protobuf:"varint,19,opt,name=transaction" json:"transaction,omitempty"`
	Timestamp            int64    `protobuf:"varint,20,opt,name=timestamp" json:"timestamp,omitempty"`
	Height               int32    `protobuf:"varint,21,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_519f42562c38e535, []int{5}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSenderPublicKey() string {
	if m != nil {
		return m.SenderPublicKey
	}
	return ""
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetFeeNQT() int64 {
	if m != nil {
		return m.FeeNQT
	}
	return 0
}

func (m *Transaction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *Transaction) GetFullHash() string {
	if m != nil {
		return m.FullHash
	}
	return ""
}

func (m *Transaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetEcBlockId() uint64 {
	if m != nil {
		return m.EcBlockId
	}
	return 0
}

func (m *Transaction) GetSignatureHash() string {
	if m != nil {
		return m.SignatureHash
	}
	return ""
}

func (m *Transaction) GetSenderRS() string {
	if m != nil {
		return m.SenderRS
	}
	return ""
}

func (m *Transaction) GetSubtype() int32 {
	if m != nil {
		return m.Subtype
	}
	return 0
}

func (m *Transaction) GetAmountNQT() int64 {
	if m != nil {
		return m.AmountNQT
	}
	return 0
}

func (m *Transaction) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Transaction) GetEcBlockHeight() int32 {
	if m != nil {
		return m.EcBlockHeight
	}
	return 0
}

func (m *Transaction) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *Transaction) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *Transaction) GetDeadline() int32 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *Transaction) GetTransaction() uint64 {
	if m != nil {
		return m.Transaction
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCumulativeDifficultyResponse)(nil), "p2p.GetCumulativeDifficultyResponse")
	proto.RegisterType((*GetNextBlocksResponse)(nil), "p2p.GetNextBlocksResponse")
	proto.RegisterType((*GetNextBlockIdsResponse)(nil), "p2p.GetNextBlockIdsResponse")
	proto.RegisterType((*GetPeers)(nil), "p2p.GetPeers")
	proto.RegisterType((*Block)(nil), "p2p.Block")
	proto.RegisterType((*Transaction)(nil), "p2p.Transaction")
}

func init() { proto.RegisterFile("api/protobuf-spec/p2p.proto", fileDescriptor_p2p_519f42562c38e535) }

var fileDescriptor_p2p_519f42562c38e535 = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0x68, 0xba, 0xad, 0xa7, 0xdd, 0xd6, 0x79, 0x1b, 0x58, 0x30, 0x89, 0x2a, 0x42, 0xa8,
	0x42, 0xb0, 0xa1, 0xc2, 0x2d, 0x17, 0x63, 0x88, 0x0d, 0x81, 0xa6, 0x91, 0xf5, 0x05, 0xdc, 0xf4,
	0xb4, 0xb5, 0x48, 0x9d, 0x28, 0x76, 0x26, 0x7a, 0xc9, 0xc3, 0xf1, 0x28, 0xbc, 0x07, 0xf2, 0x71,
	0x9a, 0x9f, 0xae, 0x77, 0x39, 0xdf, 0xb1, 0xcf, 0xcf, 0xf7, 0x7d, 0x0e, 0xbc, 0x10, 0xa9, 0xbc,
	0x48, 0xb3, 0xc4, 0x24, 0x93, 0x7c, 0xf6, 0x4e, 0xa7, 0x18, 0x5d, 0xa4, 0xa3, 0xf4, 0x9c, 0x10,
	0xd6, 0x4a, 0x47, 0x69, 0xf0, 0xc7, 0x83, 0x97, 0xd7, 0x68, 0xae, 0xf2, 0x65, 0x1e, 0x0b, 0x23,
	0x1f, 0xf0, 0x8b, 0x9c, 0xcd, 0x64, 0x94, 0xc7, 0x66, 0x15, 0xa2, 0x4e, 0x13, 0xa5, 0x91, 0xbd,
	0x81, 0xfe, 0x24, 0x4e, 0xa2, 0x5f, 0xd1, 0x42, 0x48, 0x75, 0x83, 0x72, 0xbe, 0x30, 0xdc, 0x1b,
	0x78, 0xc3, 0x76, 0xf8, 0x08, 0x67, 0x23, 0x38, 0x89, 0xb6, 0xd4, 0xe2, 0x4f, 0x06, 0xde, 0xb0,
	0x13, 0x6e, 0xcd, 0x05, 0x57, 0x70, 0x7a, 0x8d, 0xe6, 0x16, 0x7f, 0x9b, 0xcf, 0xb6, 0x9c, 0xae,
	0x35, 0x06, 0x55, 0xa2, 0xdc, 0x1b, 0xb4, 0x86, 0xdd, 0x11, 0x9c, 0xdb, 0x0d, 0x08, 0x0a, 0x6b,
	0xd9, 0xe0, 0x13, 0x3c, 0xab, 0x17, 0xf9, 0x36, 0xad, 0xca, 0x04, 0xd0, 0x53, 0x35, 0x9c, 0x0a,
	0xf9, 0x61, 0x03, 0x0b, 0x06, 0xb0, 0x77, 0x8d, 0xe6, 0x0e, 0x31, 0xd3, 0xec, 0x04, 0xda, 0xa9,
	0xfd, 0xa0, 0x83, 0x9d, 0xd0, 0x05, 0xc1, 0x5f, 0x1f, 0xda, 0x74, 0x9c, 0xbd, 0x82, 0xfd, 0x54,
	0xac, 0xe2, 0x44, 0x4c, 0x7f, 0xa0, 0x9a, 0x9b, 0x05, 0x91, 0xd1, 0x0a, 0x9b, 0x20, 0x7b, 0x0d,
	0x07, 0x26, 0x31, 0x22, 0xbe, 0x5c, 0x26, 0xb9, 0x32, 0xb7, 0x3f, 0xc7, 0xc4, 0x41, 0x2b, 0xdc,
	0x40, 0xd9, 0x7b, 0x38, 0x9e, 0xa3, 0xc2, 0x4c, 0x18, 0x99, 0xa8, 0x7b, 0x39, 0x57, 0xc2, 0xe4,
	0x19, 0xf2, 0x16, 0x11, 0xb6, 0x2d, 0xc5, 0xce, 0x81, 0x15, 0x70, 0x92, 0xdd, 0xe5, 0x93, 0x58,
	0x46, 0xdf, 0x71, 0xc5, 0x7d, 0xba, 0xb0, 0x25, 0xc3, 0x06, 0xd0, 0x2d, 0x46, 0xbb, 0x11, 0x7a,
	0xc1, 0xdb, 0x74, 0xb0, 0x0e, 0xd9, 0x59, 0x49, 0xc9, 0xaa, 0xfd, 0x0e, 0x1d, 0xda, 0x40, 0xd9,
	0x47, 0xe8, 0x99, 0x4c, 0x28, 0x2d, 0x22, 0x3b, 0x91, 0xe6, 0xbb, 0x24, 0x49, 0x9f, 0x24, 0x19,
	0x57, 0x89, 0xb0, 0x71, 0x8a, 0x71, 0xd8, 0x7d, 0xc0, 0x4c, 0xcb, 0x44, 0xf1, 0x3d, 0xb2, 0xcd,
	0x3a, 0xb4, 0x4c, 0xab, 0x44, 0x45, 0xc8, 0x3b, 0xd4, 0xce, 0x05, 0x76, 0x5e, 0xe2, 0xe8, 0x2b,
	0xa2, 0xa5, 0x0d, 0x88, 0xb6, 0x3a, 0xc4, 0x9e, 0xc3, 0x1e, 0x4d, 0x76, 0x39, 0xd6, 0xbc, 0x4b,
	0x22, 0x95, 0x31, 0xa9, 0x93, 0xe1, 0x83, 0x4c, 0x72, 0x4d, 0x72, 0xf1, 0xde, 0xc0, 0x1b, 0xfa,
	0x61, 0x13, 0x64, 0x67, 0xd0, 0x31, 0x72, 0x89, 0xda, 0x88, 0x65, 0xca, 0xf7, 0xa9, 0x43, 0x05,
	0xd8, 0xb9, 0xa8, 0x1e, 0x3f, 0xa0, 0xbb, 0x2e, 0x60, 0x4f, 0x61, 0x67, 0xe1, 0xdc, 0x7f, 0x48,
	0x6b, 0x14, 0x11, 0x7b, 0x0b, 0x47, 0x8d, 0xe2, 0xc4, 0x72, 0x9f, 0x36, 0x7a, 0x9c, 0x08, 0xfe,
	0xf9, 0xd0, 0xad, 0x71, 0xc5, 0x86, 0x70, 0xa8, 0x51, 0x4d, 0xb1, 0x26, 0xa5, 0x47, 0x77, 0x37,
	0x61, 0x3b, 0xb3, 0x2e, 0x05, 0x72, 0x0f, 0xaa, 0x02, 0xec, 0x74, 0x33, 0x47, 0x58, 0x8b, 0xd6,
	0x29, 0x22, 0xc6, 0xc0, 0x37, 0xab, 0x14, 0xc9, 0x1f, 0xed, 0x90, 0xbe, 0x2d, 0x47, 0x51, 0xa2,
	0x66, 0x32, 0x5b, 0x0a, 0x27, 0x64, 0x9b, 0x92, 0x4d, 0xd0, 0xb2, 0x3c, 0xcb, 0xe3, 0x98, 0xd6,
	0x71, 0x7e, 0x28, 0xe3, 0xba, 0xa6, 0xbb, 0x4d, 0x4d, 0xcf, 0xa0, 0x83, 0x51, 0xf1, 0xae, 0x48,
	0x6f, 0x3f, 0xac, 0x00, 0xdb, 0xb9, 0x1c, 0x99, 0x0a, 0x3b, 0xe5, 0x9b, 0xa0, 0xed, 0xec, 0x96,
	0x0f, 0xef, 0x79, 0xd7, 0x75, 0x5e, 0xc7, 0xb6, 0xb3, 0xce, 0x27, 0xb4, 0x52, 0xcf, 0x75, 0x2e,
	0x42, 0xdb, 0x59, 0x94, 0x8f, 0xad, 0xd0, 0xb4, 0x04, 0x2c, 0x3f, 0xae, 0x46, 0x21, 0x6a, 0x11,
	0xd9, 0x89, 0x8a, 0xf1, 0x6e, 0xea, 0xe2, 0x36, 0xc1, 0xca, 0x11, 0xfd, 0xba, 0x23, 0xd6, 0xef,
	0x66, 0x5c, 0x5a, 0xe9, 0xc8, 0xbd, 0xf1, 0x26, 0x6a, 0xf7, 0x99, 0xa2, 0x98, 0xc6, 0x52, 0x21,
	0x67, 0x54, 0xbe, 0x8c, 0xc9, 0xed, 0x95, 0x1d, 0xf8, 0x31, 0xd5, 0xaf, 0x43, 0x4d, 0xaf, 0x9e,
	0x6c, 0x7a, 0xb5, 0x72, 0xe5, 0x69, 0xdd, 0x95, 0x93, 0x1d, 0xfa, 0xcb, 0x7f, 0xf8, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0x2e, 0x66, 0x4b, 0x6b, 0x04, 0x06, 0x00, 0x00,
}
