// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCumulativeDifficultyResponse struct {
	BlockchainHeight     int32    `protobuf:"varint,1,opt,name=blockchainHeight" json:"blockchainHeight,omitempty"`
	CumulativeDifficulty string   `protobuf:"bytes,2,opt,name=cumulativeDifficulty" json:"cumulativeDifficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCumulativeDifficultyResponse) Reset()         { *m = GetCumulativeDifficultyResponse{} }
func (m *GetCumulativeDifficultyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCumulativeDifficultyResponse) ProtoMessage()    {}
func (*GetCumulativeDifficultyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_5fbaa0ee36e9ed68, []int{0}
}
func (m *GetCumulativeDifficultyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Unmarshal(m, b)
}
func (m *GetCumulativeDifficultyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Marshal(b, m, deterministic)
}
func (dst *GetCumulativeDifficultyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCumulativeDifficultyResponse.Merge(dst, src)
}
func (m *GetCumulativeDifficultyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCumulativeDifficultyResponse.Size(m)
}
func (m *GetCumulativeDifficultyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCumulativeDifficultyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCumulativeDifficultyResponse proto.InternalMessageInfo

func (m *GetCumulativeDifficultyResponse) GetBlockchainHeight() int32 {
	if m != nil {
		return m.BlockchainHeight
	}
	return 0
}

func (m *GetCumulativeDifficultyResponse) GetCumulativeDifficulty() string {
	if m != nil {
		return m.CumulativeDifficulty
	}
	return ""
}

type GetNextBlocksResponse struct {
	NextBlocks           []*Block `protobuf:"bytes,1,rep,name=nextBlocks" json:"nextBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNextBlocksResponse) Reset()         { *m = GetNextBlocksResponse{} }
func (m *GetNextBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetNextBlocksResponse) ProtoMessage()    {}
func (*GetNextBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_5fbaa0ee36e9ed68, []int{1}
}
func (m *GetNextBlocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNextBlocksResponse.Unmarshal(m, b)
}
func (m *GetNextBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNextBlocksResponse.Marshal(b, m, deterministic)
}
func (dst *GetNextBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNextBlocksResponse.Merge(dst, src)
}
func (m *GetNextBlocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetNextBlocksResponse.Size(m)
}
func (m *GetNextBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNextBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNextBlocksResponse proto.InternalMessageInfo

func (m *GetNextBlocksResponse) GetNextBlocks() []*Block {
	if m != nil {
		return m.NextBlocks
	}
	return nil
}

type Block struct {
	PayloadLength       int64          `protobuf:"varint,1,opt,name=payloadLength" json:"payloadLength,omitempty"`
	TotalAmountNQT      int64          `protobuf:"varint,2,opt,name=totalAmountNQT" json:"totalAmountNQT,omitempty"`
	GenerationSignature string         `protobuf:"bytes,3,opt,name=generationSignature" json:"generationSignature,omitempty"`
	GeneratorPublicKey  string         `protobuf:"bytes,4,opt,name=generatorPublicKey" json:"generatorPublicKey,omitempty"`
	PayloadHash         string         `protobuf:"bytes,5,opt,name=payloadHash" json:"payloadHash,omitempty"`
	BlockSignature      string         `protobuf:"bytes,6,opt,name=BlockSignature" json:"BlockSignature,omitempty"`
	Transactions        []*Transaction `protobuf:"bytes,7,rep,name=Transactions" json:"Transactions,omitempty"`
	Version             int32          `protobuf:"varint,8,opt,name=Version" json:"Version,omitempty"`
	Nonce               string         `protobuf:"bytes,9,opt,name=Nonce" json:"Nonce,omitempty"`
	TotalFeeNQT         int64          `protobuf:"varint,10,opt,name=TotalFeeNQT" json:"TotalFeeNQT,omitempty"`
	// BlockATs = 11;
	PreviousBlock        string   `protobuf:"bytes,12,opt,name=PreviousBlock" json:"PreviousBlock,omitempty"`
	Timestamp            int64    `protobuf:"varint,13,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Block                int64    `protobuf:"varint,14,opt,name=Block" json:"Block,omitempty"`
	Height               int32    `protobuf:"varint,15,opt,name=Height" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_5fbaa0ee36e9ed68, []int{2}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetPayloadLength() int64 {
	if m != nil {
		return m.PayloadLength
	}
	return 0
}

func (m *Block) GetTotalAmountNQT() int64 {
	if m != nil {
		return m.TotalAmountNQT
	}
	return 0
}

func (m *Block) GetGenerationSignature() string {
	if m != nil {
		return m.GenerationSignature
	}
	return ""
}

func (m *Block) GetGeneratorPublicKey() string {
	if m != nil {
		return m.GeneratorPublicKey
	}
	return ""
}

func (m *Block) GetPayloadHash() string {
	if m != nil {
		return m.PayloadHash
	}
	return ""
}

func (m *Block) GetBlockSignature() string {
	if m != nil {
		return m.BlockSignature
	}
	return ""
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Block) GetTotalFeeNQT() int64 {
	if m != nil {
		return m.TotalFeeNQT
	}
	return 0
}

func (m *Block) GetPreviousBlock() string {
	if m != nil {
		return m.PreviousBlock
	}
	return ""
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetBlock() int64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *Block) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Transaction struct {
	SenderPublicKey string `protobuf:"bytes,1,opt,name=senderPublicKey" json:"senderPublicKey,omitempty"`
	Signature       string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	FeeNQT          int64  `protobuf:"varint,3,opt,name=feeNQT" json:"feeNQT,omitempty"`
	Type            int32  `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	Confirmations   int32  `protobuf:"varint,5,opt,name=confirmations" json:"confirmations,omitempty"`
	FullHash        string `protobuf:"bytes,6,opt,name=fullHash" json:"fullHash,omitempty"`
	Version         int32  `protobuf:"varint,7,opt,name=version" json:"version,omitempty"`
	EcBlockId       string `protobuf:"bytes,8,opt,name=ecBlockId" json:"ecBlockId,omitempty"`
	SignatureHash   string `protobuf:"bytes,9,opt,name=signatureHash" json:"signatureHash,omitempty"`
	// attachment = 10;
	SenderRS             string   `protobuf:"bytes,11,opt,name=senderRS" json:"senderRS,omitempty"`
	Subtype              int32    `protobuf:"varint,12,opt,name=subtype" json:"subtype,omitempty"`
	AmountNQT            int64    `protobuf:"varint,13,opt,name=amountNQT" json:"amountNQT,omitempty"`
	Sender               int64    `protobuf:"varint,14,opt,name=sender" json:"sender,omitempty"`
	EcBlockHeight        int32    `protobuf:"varint,15,opt,name=ecBlockHeight" json:"ecBlockHeight,omitempty"`
	Block                int64    `protobuf:"varint,16,opt,name=block" json:"block,omitempty"`
	BlockTimestamp       int64    `protobuf:"varint,17,opt,name=blockTimestamp" json:"blockTimestamp,omitempty"`
	Deadline             int32    `protobuf:"varint,18,opt,name=deadline" json:"deadline,omitempty"`
	Transaction          int64    `protobuf:"varint,19,opt,name=transaction" json:"transaction,omitempty"`
	Timestamp            int64    `protobuf:"varint,20,opt,name=timestamp" json:"timestamp,omitempty"`
	Height               int32    `protobuf:"varint,21,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_5fbaa0ee36e9ed68, []int{3}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSenderPublicKey() string {
	if m != nil {
		return m.SenderPublicKey
	}
	return ""
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetFeeNQT() int64 {
	if m != nil {
		return m.FeeNQT
	}
	return 0
}

func (m *Transaction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *Transaction) GetFullHash() string {
	if m != nil {
		return m.FullHash
	}
	return ""
}

func (m *Transaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetEcBlockId() string {
	if m != nil {
		return m.EcBlockId
	}
	return ""
}

func (m *Transaction) GetSignatureHash() string {
	if m != nil {
		return m.SignatureHash
	}
	return ""
}

func (m *Transaction) GetSenderRS() string {
	if m != nil {
		return m.SenderRS
	}
	return ""
}

func (m *Transaction) GetSubtype() int32 {
	if m != nil {
		return m.Subtype
	}
	return 0
}

func (m *Transaction) GetAmountNQT() int64 {
	if m != nil {
		return m.AmountNQT
	}
	return 0
}

func (m *Transaction) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *Transaction) GetEcBlockHeight() int32 {
	if m != nil {
		return m.EcBlockHeight
	}
	return 0
}

func (m *Transaction) GetBlock() int64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *Transaction) GetBlockTimestamp() int64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *Transaction) GetDeadline() int32 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *Transaction) GetTransaction() int64 {
	if m != nil {
		return m.Transaction
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCumulativeDifficultyResponse)(nil), "p2p.GetCumulativeDifficultyResponse")
	proto.RegisterType((*GetNextBlocksResponse)(nil), "p2p.GetNextBlocksResponse")
	proto.RegisterType((*Block)(nil), "p2p.Block")
	proto.RegisterType((*Transaction)(nil), "p2p.Transaction")
}

func init() { proto.RegisterFile("api/protobuf-spec/p2p.proto", fileDescriptor_p2p_5fbaa0ee36e9ed68) }

var fileDescriptor_p2p_5fbaa0ee36e9ed68 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xc9, 0xb2, 0xad, 0xee, 0xbe, 0xf0, 0x36, 0x64, 0x01, 0x12, 0x55, 0x85, 0x50, 0x85,
	0xc4, 0x86, 0x0a, 0x7f, 0x00, 0x86, 0xd8, 0x10, 0x68, 0x1a, 0x59, 0xc5, 0xbb, 0x9b, 0xde, 0xb4,
	0x16, 0xa9, 0x1d, 0xc5, 0xce, 0x44, 0x1f, 0xf9, 0xb1, 0xfc, 0x0a, 0x5e, 0xd0, 0xbd, 0xf6, 0xf2,
	0x31, 0xfa, 0x96, 0x7b, 0x6e, 0xec, 0x73, 0xce, 0x3d, 0x37, 0x61, 0xcf, 0x64, 0xa1, 0xce, 0x8b,
	0xd2, 0x38, 0x33, 0xab, 0xb2, 0x37, 0xb6, 0x80, 0xf4, 0xbc, 0x98, 0x14, 0x67, 0x84, 0xf0, 0xa8,
	0x98, 0x14, 0xa3, 0xdf, 0x3d, 0xf6, 0xe2, 0x12, 0xdc, 0x45, 0xb5, 0xaa, 0x72, 0xe9, 0xd4, 0x1d,
	0x7c, 0x52, 0x59, 0xa6, 0xd2, 0x2a, 0x77, 0xeb, 0x04, 0x6c, 0x61, 0xb4, 0x05, 0xfe, 0x9a, 0x1d,
	0xcd, 0x72, 0x93, 0xfe, 0x4c, 0x97, 0x52, 0xe9, 0x2b, 0x50, 0x8b, 0xa5, 0x13, 0xbd, 0x61, 0x6f,
	0x1c, 0x27, 0xff, 0xe1, 0x7c, 0xc2, 0x4e, 0xd2, 0x0d, 0x77, 0x89, 0x47, 0xc3, 0xde, 0xb8, 0x9f,
	0x6c, 0xec, 0x8d, 0x2e, 0xd8, 0xe9, 0x25, 0xb8, 0x6b, 0xf8, 0xe5, 0x3e, 0xe2, 0x75, 0xb6, 0x45,
	0xcc, 0x74, 0x8d, 0x8a, 0xde, 0x30, 0x1a, 0x0f, 0x26, 0xec, 0x0c, 0x1d, 0x10, 0x94, 0xb4, 0xba,
	0xa3, 0xbf, 0x11, 0x8b, 0xe9, 0x91, 0xbf, 0x64, 0xfb, 0x85, 0x5c, 0xe7, 0x46, 0xce, 0xbf, 0x81,
	0x5e, 0xb8, 0x25, 0x69, 0x8d, 0x92, 0x2e, 0xc8, 0x5f, 0xb1, 0x03, 0x67, 0x9c, 0xcc, 0x3f, 0xac,
	0x4c, 0xa5, 0xdd, 0xf5, 0xf7, 0x29, 0x49, 0x8c, 0x92, 0x07, 0x28, 0x7f, 0xcb, 0x8e, 0x17, 0xa0,
	0xa1, 0x94, 0x4e, 0x19, 0x7d, 0xab, 0x16, 0x5a, 0xba, 0xaa, 0x04, 0x11, 0x91, 0x9f, 0x4d, 0x2d,
	0x7e, 0xc6, 0x78, 0x80, 0x4d, 0x79, 0x53, 0xcd, 0x72, 0x95, 0x7e, 0x85, 0xb5, 0xd8, 0xa2, 0x03,
	0x1b, 0x3a, 0x7c, 0xc8, 0x06, 0x41, 0xda, 0x95, 0xb4, 0x4b, 0x11, 0xd3, 0x8b, 0x6d, 0x08, 0xb5,
	0x92, 0xb5, 0x86, 0x7e, 0x9b, 0x5e, 0x7a, 0x80, 0xf2, 0xf7, 0x6c, 0x6f, 0x5a, 0x4a, 0x6d, 0x65,
	0x8a, 0x8a, 0xac, 0xd8, 0xa1, 0x89, 0x1d, 0xd1, 0xc4, 0x5a, 0x8d, 0xa4, 0xf3, 0x16, 0x17, 0x6c,
	0xe7, 0x07, 0x94, 0x56, 0x19, 0x2d, 0x76, 0x29, 0xd5, 0xfb, 0x92, 0x9f, 0xb0, 0xf8, 0xda, 0xe8,
	0x14, 0x44, 0x9f, 0xe8, 0x7c, 0x81, 0x7a, 0xa7, 0x38, 0xa3, 0xcf, 0x00, 0x38, 0x36, 0x46, 0x63,
	0x6b, 0x43, 0x98, 0xc0, 0x4d, 0x09, 0x77, 0xca, 0x54, 0x96, 0x14, 0x8a, 0x3d, 0x3a, 0xdf, 0x05,
	0xf9, 0x73, 0xd6, 0x9f, 0xaa, 0x15, 0x58, 0x27, 0x57, 0x85, 0xd8, 0xa7, 0x5b, 0x1a, 0x00, 0xb9,
	0xfd, 0xd9, 0x03, 0xea, 0x84, 0x6c, 0x9f, 0xb0, 0xed, 0xb0, 0x80, 0x87, 0x24, 0x35, 0x54, 0xa3,
	0x3f, 0x5b, 0x6c, 0xd0, 0x32, 0xc5, 0xc7, 0xec, 0xd0, 0x82, 0x9e, 0x43, 0x2b, 0x80, 0x1e, 0x69,
	0x78, 0x08, 0xa3, 0x0a, 0x5b, 0x8f, 0xd5, 0x6f, 0x69, 0x03, 0x20, 0x5f, 0xe6, 0x6d, 0x46, 0x24,
	0x23, 0x54, 0x9c, 0xb3, 0x2d, 0xb7, 0x2e, 0x80, 0x52, 0x8d, 0x13, 0x7a, 0x46, 0xd7, 0xa9, 0xd1,
	0x99, 0x2a, 0x57, 0xd2, 0x8f, 0x3f, 0xa6, 0x66, 0x17, 0xe4, 0x4f, 0xd9, 0x6e, 0x56, 0xe5, 0x39,
	0x45, 0xed, 0x53, 0xac, 0x6b, 0x4c, 0xe2, 0x2e, 0x24, 0xb1, 0xe3, 0x93, 0x08, 0x25, 0xaa, 0x84,
	0x94, 0x46, 0xf0, 0x65, 0x4e, 0x29, 0xf5, 0x93, 0x06, 0x40, 0xe6, 0x5a, 0x32, 0x5d, 0xec, 0xf3,
	0xea, 0x82, 0xc8, 0xec, 0xcd, 0x27, 0xb7, 0x62, 0xe0, 0x99, 0xef, 0x6b, 0x64, 0xb6, 0xd5, 0x8c,
	0x2c, 0xed, 0x79, 0xe6, 0x50, 0x22, 0xb3, 0xac, 0x3f, 0x91, 0x90, 0x52, 0x0d, 0xe0, 0x7c, 0xfc,
	0x1d, 0x21, 0xa6, 0x50, 0xa1, 0xa2, 0x20, 0xaf, 0x13, 0x57, 0x17, 0xc4, 0x8c, 0xe9, 0x07, 0x22,
	0x8e, 0x7c, 0xc6, 0x54, 0xe0, 0xb6, 0xd3, 0x43, 0xb3, 0x1c, 0x8f, 0xfd, 0x97, 0xd9, 0x45, 0xd1,
	0xcf, 0x1c, 0xe4, 0x3c, 0x57, 0x1a, 0x04, 0xa7, 0xeb, 0xeb, 0x1a, 0x77, 0xd4, 0x35, 0xeb, 0x20,
	0x8e, 0xfd, 0x8e, 0xb6, 0x20, 0xf4, 0xe5, 0x6a, 0x82, 0x13, 0xef, 0xab, 0x06, 0xd0, 0xd7, 0xd2,
	0x0b, 0x3f, 0xf5, 0x7b, 0xe6, 0xab, 0xd9, 0x36, 0xfd, 0x3a, 0xdf, 0xfd, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0xb9, 0xf4, 0xf3, 0x59, 0x05, 0x00, 0x00,
}
